//! `GithubInvitation` Virtual Object: create, on_webhook, cancel, tick_expire.

use crate::audit::{Actor, Target};
use crate::impl_restate_json_payload;
use crate::state::AppState;
use audit::EventType;
use chrono::{DateTime, Utc};
// Aliased to avoid colliding with the `GithubInvitation` trait generated by
// `#[restate_sdk::object]` below.
use domain::GithubInvitation as DomainGithubInvitation;
use domain::{GithubInvitationId, InvitationState, RequestId};
use restate_sdk::context::{ContextSideEffects, ObjectContext, RunFuture};
use restate_sdk::errors::TerminalError;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CreateInvitationInput {
    pub invitation_id: GithubInvitationId,
    pub invitation_request_id: RequestId,
    pub installation_id: u64,
    pub repo_id: u64,
    pub repo_full_name: String, // "owner/name"
    pub recipient_login: String,
    pub permission: domain::Permission,
    pub now: DateTime<Utc>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct OnWebhookInput {
    pub invitation_id: GithubInvitationId,
    pub action: WebhookAction,
    pub at: DateTime<Utc>,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum WebhookAction {
    Accepted,
    Declined,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CancelInvitationInput {
    pub invitation_id: GithubInvitationId,
    pub installation_id: u64,
    pub by_user: Option<u64>, // None when system-cancelled (cascade in v2)
    pub at: DateTime<Utc>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TickExpireInput {
    pub invitation_id: GithubInvitationId,
    pub installation_id: u64,
    pub at: DateTime<Utc>,
}

impl_restate_json_payload!(CreateInvitationInput);
impl_restate_json_payload!(OnWebhookInput);
impl_restate_json_payload!(CancelInvitationInput);
impl_restate_json_payload!(TickExpireInput);

/// Split a `repo_full_name` of the form `"owner/name"` into its components.
/// GitHub guarantees this format; an unsplit string surfaces as an Invariant.
fn split_full_name(full_name: &str) -> crate::error::Result<(&str, &str)> {
    full_name.split_once('/').ok_or_else(|| {
        crate::error::HandlerError::Invariant(format!(
            "repo_full_name not in owner/name form: {full_name:?}"
        ))
    })
}

#[restate_sdk::object]
pub trait GithubInvitation {
    async fn create(input: CreateInvitationInput) -> std::result::Result<(), TerminalError>;
    async fn on_webhook(input: OnWebhookInput) -> std::result::Result<(), TerminalError>;
    async fn cancel(input: CancelInvitationInput) -> std::result::Result<(), TerminalError>;
    async fn tick_expire(input: TickExpireInput) -> std::result::Result<(), TerminalError>;
}

pub struct GithubInvitationImpl {
    pub state: AppState,
}

impl GithubInvitation for GithubInvitationImpl {
    async fn create(
        &self,
        ctx: ObjectContext<'_>,
        input: CreateInvitationInput,
    ) -> std::result::Result<(), TerminalError> {
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            create_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("create")
        .await
    }

    async fn on_webhook(
        &self,
        ctx: ObjectContext<'_>,
        input: OnWebhookInput,
    ) -> std::result::Result<(), TerminalError> {
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            on_webhook_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("on_webhook")
        .await
    }

    async fn cancel(
        &self,
        ctx: ObjectContext<'_>,
        input: CancelInvitationInput,
    ) -> std::result::Result<(), TerminalError> {
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            cancel_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("cancel")
        .await
    }

    async fn tick_expire(
        &self,
        ctx: ObjectContext<'_>,
        input: TickExpireInput,
    ) -> std::result::Result<(), TerminalError> {
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            tick_expire_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("tick_expire")
        .await
    }
}

/// Pure logic: row-insert in `Sending`, call GitHub, branch on status, update
/// row + audit. Returns `Ok(())` for both 201 (sent) and 204 (already a
/// collaborator) paths. Terminal 4xx is recorded as Failed and returns Ok so
/// Restate does NOT retry. Transient 5xx returns Err to trigger Restate retry.
pub async fn create_logic(
    state: &AppState,
    input: &CreateInvitationInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    // Row insert in `Sending` state. Idempotent under retry: if the row
    // already exists with `id = input.invitation_id`, storage returns
    // `Conflict::DuplicateId` and we proceed (Restate retried after the
    // GitHub call succeeded but before the row update).
    let row = DomainGithubInvitation {
        id: input.invitation_id,
        invitation_request_id: input.invitation_request_id,
        repo_id: input.repo_id,
        github_invitation_id: None,
        state: InvitationState::Sending,
        error_message: None,
        created_at: input.now,
        updated_at: input.now,
    };
    match state.storage.insert_github_invitation(&row).await {
        Ok(()) => (),
        Err(storage::Error::Conflict(storage::ConflictKind::DuplicateId)) => {
            // Re-entry; row already in some state. Read it; if terminal, no-op.
            let existing = state
                .storage
                .get_github_invitation(input.invitation_id)
                .await?
                .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;
            if existing.state.is_terminal() {
                return Ok(());
            }
            // Fall through and re-attempt the GitHub call.
        }
        Err(e) => return Err(e.into()),
    }

    let (owner, repo) = split_full_name(&input.repo_full_name)?;

    let outcome = state
        .github
        .add_collaborator(
            input.installation_id,
            owner,
            repo,
            &input.recipient_login,
            input.permission,
        )
        .await;

    let account_id = lookup_account_id_for_installation(state, input.installation_id).await?;

    match outcome {
        Ok(Some(github_id)) => {
            // 201 — invitation pending.
            state
                .storage
                .update_github_invitation(&storage::GithubInvitationUpdate {
                    id: input.invitation_id,
                    state: InvitationState::Sent,
                    github_invitation_id: Some(github_id),
                    error_message: None,
                    updated_at: input.now,
                })
                .await?;
            crate::audit::emit(
                state,
                account_id,
                EventType::InvitationSent,
                Actor::System,
                Target::github_invitation(input.invitation_id),
                serde_json::json!({
                    "github_invitation_id": github_id,
                    "repo_full_name": input.repo_full_name,
                    "recipient": input.recipient_login,
                }),
                request_id,
            )
            .await?;
        }
        Ok(None) => {
            // 204 — already a collaborator.
            state
                .storage
                .update_github_invitation(&storage::GithubInvitationUpdate {
                    id: input.invitation_id,
                    state: InvitationState::Accepted,
                    github_invitation_id: None,
                    error_message: None,
                    updated_at: input.now,
                })
                .await?;
            crate::audit::emit(
                state,
                account_id,
                EventType::InvitationAccepted,
                Actor::Github,
                Target::github_invitation(input.invitation_id),
                serde_json::json!({
                    "reason": "already_collaborator",
                    "repo_full_name": input.repo_full_name,
                    "recipient": input.recipient_login,
                }),
                request_id,
            )
            .await?;
        }
        Err(e) => {
            let h: crate::error::HandlerError = e.into();
            if !h.is_terminal() {
                // Transient — let Restate retry.
                return Err(h);
            }
            // Terminal 4xx — mark failed, audit, return Ok so Restate doesn't retry.
            let msg = h.to_string();
            state
                .storage
                .update_github_invitation(&storage::GithubInvitationUpdate {
                    id: input.invitation_id,
                    state: InvitationState::Failed,
                    github_invitation_id: None,
                    error_message: Some(msg.clone()),
                    updated_at: input.now,
                })
                .await?;
            crate::audit::emit(
                state,
                account_id,
                EventType::InvitationSendFailed,
                Actor::System,
                Target::github_invitation(input.invitation_id),
                serde_json::json!({
                    "error": msg,
                    "repo_full_name": input.repo_full_name,
                    "recipient": input.recipient_login,
                }),
                request_id,
            )
            .await?;
        }
    }

    Ok(())
}

/// Helper: resolve account_id from an installation_id by direct lookup.
/// Returns terminal `NotFound` if the installation row is unknown.
async fn lookup_account_id_for_installation(
    state: &AppState,
    installation_id: u64,
) -> crate::error::Result<u64> {
    let acct = state
        .storage
        .get_installation(installation_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;
    Ok(acct.account_id)
}

/// Pure logic: transition the github_invitation row based on a webhook
/// signal. Idempotent: if the row is already in a terminal state, no-op.
pub async fn on_webhook_logic(
    state: &AppState,
    input: &OnWebhookInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    let row = state
        .storage
        .get_github_invitation(input.invitation_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;

    if row.state.is_terminal() {
        return Ok(()); // already settled; webhook is just confirming.
    }

    let new_state = match input.action {
        WebhookAction::Accepted => InvitationState::Accepted,
        WebhookAction::Declined => InvitationState::Declined,
    };
    state
        .storage
        .update_github_invitation(&storage::GithubInvitationUpdate {
            id: input.invitation_id,
            state: new_state,
            github_invitation_id: None,
            error_message: None,
            updated_at: input.at,
        })
        .await?;

    let event_type = match new_state {
        InvitationState::Accepted => EventType::InvitationAccepted,
        InvitationState::Declined => EventType::InvitationDeclined,
        _ => unreachable!("WebhookAction maps to Accepted/Declined"),
    };

    // Resolve account_id by walking row -> request -> link.
    let request = state
        .storage
        .get_invitation_request(row.invitation_request_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;
    let link = state
        .storage
        .get_share_link_by_id(request.share_link_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;

    crate::audit::emit(
        state,
        link.account_id,
        event_type,
        Actor::Github,
        Target::github_invitation(input.invitation_id),
        serde_json::json!({}),
        request_id,
    )
    .await
}

/// Pure logic: cancel a pending GitHub invitation. Calls
/// `DELETE /repos/.../invitations/{github_id}`; marks row cancelled; emits
/// `invitation.cancelled`. Idempotent: if the row is already terminal
/// or the GitHub invitation is gone (404), proceeds to mark cancelled
/// without re-deleting.
pub async fn cancel_logic(
    state: &AppState,
    input: &CancelInvitationInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    let row = state
        .storage
        .get_github_invitation(input.invitation_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;

    if row.state.is_terminal() {
        return Ok(());
    }

    // Look up the repo full name from the invitation_request → share_link.repos chain.
    let request = state
        .storage
        .get_invitation_request(row.invitation_request_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;
    let link = state
        .storage
        .get_share_link_by_id(request.share_link_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;
    let repo = link
        .repos
        .iter()
        .find(|r| r.repo_id == row.repo_id)
        .ok_or_else(|| {
            crate::error::HandlerError::Invariant(format!(
                "github_invitation {} references repo_id {} not in link.repos",
                input.invitation_id, row.repo_id
            ))
        })?;
    let (owner, repo_name) = split_full_name(&repo.repo_full_name)?;

    // Call GitHub if we know the upstream id; otherwise skip (row was Sending
    // and never got a 201, so nothing to delete).
    if let Some(github_id) = row.github_invitation_id {
        match state
            .github
            .delete_invitation(input.installation_id, owner, repo_name, github_id)
            .await
        {
            Ok(()) => (),
            Err(github::Error::Status { status: 404, .. }) => {
                // Already cancelled / accepted / declined upstream; proceed.
            }
            Err(e) => {
                let h: crate::error::HandlerError = e.into();
                if !h.is_terminal() {
                    return Err(h);
                }
                // Other 4xx — proceed to mark cancelled, audit reason.
            }
        }
    }

    state
        .storage
        .update_github_invitation(&storage::GithubInvitationUpdate {
            id: input.invitation_id,
            state: InvitationState::Cancelled,
            github_invitation_id: None,
            error_message: None,
            updated_at: input.at,
        })
        .await?;

    let actor = match input.by_user {
        Some(uid) => Actor::User(uid),
        None => Actor::System,
    };
    crate::audit::emit(
        state,
        link.account_id,
        EventType::InvitationCancelled,
        actor,
        Target::github_invitation(input.invitation_id),
        serde_json::json!({}),
        request_id,
    )
    .await
}

/// Pure logic: at expiration time, confirm via GitHub list_invitations that
/// the row is still pending; if so, mark expired + audit.
pub async fn tick_expire_logic(
    state: &AppState,
    input: &TickExpireInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    let row = state
        .storage
        .get_github_invitation(input.invitation_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;

    if row.state.is_terminal() {
        return Ok(());
    }

    let request = state
        .storage
        .get_invitation_request(row.invitation_request_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;
    let link = state
        .storage
        .get_share_link_by_id(request.share_link_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(storage::Error::NotFound))?;
    let repo = link
        .repos
        .iter()
        .find(|r| r.repo_id == row.repo_id)
        .ok_or_else(|| {
            crate::error::HandlerError::Invariant(format!(
                "github_invitation {} references repo_id {} not in link.repos",
                input.invitation_id, row.repo_id
            ))
        })?;
    let (owner, repo_name) = split_full_name(&repo.repo_full_name)?;

    let pending = state
        .github
        .list_invitations(input.installation_id, owner, repo_name)
        .await?;
    let still_pending = row
        .github_invitation_id
        .map(|id| pending.iter().any(|p| p.id == id))
        .unwrap_or(false);

    if !still_pending {
        // Either accepted/declined upstream (webhook missed) or cancelled.
        // Don't fight: leave to webhook reconciliation. Plan 6 / Reconcile.
        return Ok(());
    }

    state
        .storage
        .update_github_invitation(&storage::GithubInvitationUpdate {
            id: input.invitation_id,
            state: InvitationState::Expired,
            github_invitation_id: None,
            error_message: None,
            updated_at: input.at,
        })
        .await?;

    crate::audit::emit(
        state,
        link.account_id,
        EventType::InvitationExpired,
        Actor::System,
        Target::github_invitation(input.invitation_id),
        serde_json::json!({}),
        request_id,
    )
    .await
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::HandlerError;
    use crate::state::AppState;
    use crate::test_support::{dt, fixture_github_client, fixture_storage};
    use domain::{AccountType, Permission, SelectedRepos, ShareLinkId, Slug};
    use github::mocks::{Expectation, MockTransport};
    use github::transport::{Method, Response};
    use rand::SeedableRng;
    use std::collections::BTreeMap;
    use std::sync::Arc;

    fn token_mint(installation_id: u64) -> Expectation {
        Expectation {
            method: Method::Post,
            url: format!(
                "https://api.github.test/app/installations/{}/access_tokens",
                installation_id
            ),
            required_headers: BTreeMap::new(),
            expected_body: None,
            response: Response {
                status: 201,
                headers: BTreeMap::new(),
                body: br#"{"token":"ghs_xxx","expires_at":"2099-01-01T00:00:00Z"}"#.to_vec(),
            },
        }
    }

    /// Seed installation, user, share_link, request — all FK chain prerequisites.
    async fn seed_chain(state: &AppState) -> RequestId {
        state
            .storage
            .insert_installation(&domain::Account {
                installation_id: 9,
                account_id: 100,
                account_login: "acme".into(),
                account_type: AccountType::Organization,
                installed_at: dt("2026-05-04T12:00:00Z"),
                uninstalled_at: None,
                selected_repos: SelectedRepos::All,
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&domain::User {
                user_id: 7,
                login: "creator".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&domain::User {
                user_id: 8,
                login: "alice".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        let mut rng = rand_chacha::ChaCha8Rng::seed_from_u64(42);
        let link = domain::ShareLink {
            id: ShareLinkId::new(),
            slug: Slug::generate(&mut rng),
            installation_id: 9,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at: None,
            max_uses: None,
            uses_count: 0,
            permission: Permission::Push,
            approval_required: false,
            internal_note: None,
            revoked_at: None,
            revoked_by: None,
            repos: vec![],
        };
        state.storage.insert_share_link(&link).await.unwrap();
        let req_id = RequestId::new();
        let req = domain::InvitationRequest {
            id: req_id,
            share_link_id: link.id,
            requester_id: 8,
            justification: None,
            state: domain::RequestState::Approved,
            decided_by: Some(7),
            decided_at: Some(dt("2026-05-04T13:00:00Z")),
            decline_reason: None,
            created_at: dt("2026-05-04T12:30:00Z"),
        };
        state
            .storage
            .insert_invitation_request_and_increment_uses(&req)
            .await
            .unwrap();
        req_id
    }

    fn sample_input(
        invitation_id: GithubInvitationId,
        request_id: RequestId,
    ) -> CreateInvitationInput {
        CreateInvitationInput {
            invitation_id,
            invitation_request_id: request_id,
            installation_id: 9,
            repo_id: 10,
            repo_full_name: "acme/api".into(),
            recipient_login: "alice".into(),
            permission: Permission::Push,
            now: dt("2026-05-04T13:01:00Z"),
        }
    }

    #[tokio::test]
    async fn create_201_marks_sent_and_audits() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation {
                method: Method::Put,
                url: "https://api.github.test/repos/acme/api/collaborators/alice".into(),
                required_headers: BTreeMap::new(),
                expected_body: None,
                response: Response {
                    status: 201,
                    headers: BTreeMap::new(),
                    body: br#"{"id": 9988, "invitee":{"id":42,"login":"alice"}}"#.to_vec(),
                },
            },
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;

        let inv_id = GithubInvitationId::new();
        create_logic(&state, &sample_input(inv_id, req_id), None)
            .await
            .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Sent);
        assert_eq!(row.github_invitation_id, Some(9988));
    }

    #[tokio::test]
    async fn create_204_marks_accepted() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation {
                method: Method::Put,
                url: "https://api.github.test/repos/acme/api/collaborators/alice".into(),
                required_headers: BTreeMap::new(),
                expected_body: None,
                response: Response {
                    status: 204,
                    headers: BTreeMap::new(),
                    body: vec![],
                },
            },
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;

        let inv_id = GithubInvitationId::new();
        create_logic(&state, &sample_input(inv_id, req_id), None)
            .await
            .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Accepted);
    }

    #[tokio::test]
    async fn create_422_marks_failed_and_returns_ok() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation::status(
                Method::Put,
                "https://api.github.test/repos/acme/api/collaborators/alice",
                422,
            ),
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;

        let inv_id = GithubInvitationId::new();
        // Terminal 4xx — handler should mark failed and return Ok so Restate
        // does not retry.
        create_logic(&state, &sample_input(inv_id, req_id), None)
            .await
            .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Failed);
        assert!(row.error_message.is_some());
    }

    #[tokio::test]
    async fn create_502_propagates_transient_for_retry() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation::status(
                Method::Put,
                "https://api.github.test/repos/acme/api/collaborators/alice",
                502,
            ),
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;

        let inv_id = GithubInvitationId::new();
        let err = create_logic(&state, &sample_input(inv_id, req_id), None)
            .await
            .unwrap_err();
        assert!(!err.is_terminal(), "5xx should be transient: {err:?}");

        // The row was inserted in Sending; on retry Restate will re-call us.
        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Sending);
    }

    #[tokio::test]
    async fn create_with_bad_repo_full_name_is_invariant() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;

        let inv_id = GithubInvitationId::new();
        let mut input = sample_input(inv_id, req_id);
        input.repo_full_name = "no-slash".into();
        let err = create_logic(&state, &input, None).await.unwrap_err();
        assert!(matches!(err, HandlerError::Invariant(_)));
    }

    /// Helper: from a fresh state, get to "row in Sent state". Returns the
    /// invitation_id that subsequent webhook tests can reference.
    async fn seed_to_sent(state: &AppState, req_id: RequestId) -> GithubInvitationId {
        let inv_id = GithubInvitationId::new();
        let row = DomainGithubInvitation {
            id: inv_id,
            invitation_request_id: req_id,
            repo_id: 10,
            github_invitation_id: Some(9988),
            state: InvitationState::Sent,
            error_message: None,
            created_at: dt("2026-05-04T13:00:00Z"),
            updated_at: dt("2026-05-04T13:00:00Z"),
        };
        state.storage.insert_github_invitation(&row).await.unwrap();
        inv_id
    }

    #[tokio::test]
    async fn webhook_accepted_transitions_and_audits() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![]); // no GitHub calls in this path
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;
        let inv_id = seed_to_sent(&state, req_id).await;

        on_webhook_logic(
            &state,
            &OnWebhookInput {
                invitation_id: inv_id,
                action: WebhookAction::Accepted,
                at: dt("2026-05-04T14:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state.storage.get_github_invitation(inv_id).await.unwrap().unwrap();
        assert_eq!(row.state, InvitationState::Accepted);
    }

    #[tokio::test]
    async fn webhook_declined_transitions_and_audits() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;
        let inv_id = seed_to_sent(&state, req_id).await;

        on_webhook_logic(
            &state,
            &OnWebhookInput {
                invitation_id: inv_id,
                action: WebhookAction::Declined,
                at: dt("2026-05-04T14:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state.storage.get_github_invitation(inv_id).await.unwrap().unwrap();
        assert_eq!(row.state, InvitationState::Declined);
    }

    #[tokio::test]
    async fn webhook_on_terminal_row_is_idempotent() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;
        let inv_id = seed_to_sent(&state, req_id).await;

        // First webhook -> Accepted (terminal).
        on_webhook_logic(
            &state,
            &OnWebhookInput {
                invitation_id: inv_id,
                action: WebhookAction::Accepted,
                at: dt("2026-05-04T14:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        // Second webhook on the same row - should be a no-op, not an error.
        on_webhook_logic(
            &state,
            &OnWebhookInput {
                invitation_id: inv_id,
                action: WebhookAction::Declined,
                at: dt("2026-05-04T15:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state.storage.get_github_invitation(inv_id).await.unwrap().unwrap();
        assert_eq!(row.state, InvitationState::Accepted, "terminal state preserved");
    }

    #[tokio::test]
    async fn webhook_unknown_invitation_is_terminal() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);

        let err = on_webhook_logic(
            &state,
            &OnWebhookInput {
                invitation_id: GithubInvitationId::new(),
                action: WebhookAction::Accepted,
                at: dt("2026-05-04T14:00:00Z"),
            },
            None,
        )
        .await
        .unwrap_err();
        assert!(err.is_terminal());
    }

    /// Like `seed_to_sent` but with link.repos populated so cancel/expire can
    /// resolve the repo full name from the chain.
    async fn seed_chain_with_repos(state: &AppState) -> (RequestId, GithubInvitationId) {
        state
            .storage
            .insert_installation(&domain::Account {
                installation_id: 9,
                account_id: 100,
                account_login: "acme".into(),
                account_type: AccountType::Organization,
                installed_at: dt("2026-05-04T12:00:00Z"),
                uninstalled_at: None,
                selected_repos: SelectedRepos::All,
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&domain::User {
                user_id: 7,
                login: "creator".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&domain::User {
                user_id: 8,
                login: "alice".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        let mut rng = rand_chacha::ChaCha8Rng::seed_from_u64(7);
        let link = domain::ShareLink {
            id: ShareLinkId::new(),
            slug: Slug::generate(&mut rng),
            installation_id: 9,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at: None,
            max_uses: None,
            uses_count: 0,
            permission: Permission::Push,
            approval_required: false,
            internal_note: None,
            revoked_at: None,
            revoked_by: None,
            repos: vec![domain::ShareLinkRepo {
                repo_id: 10,
                repo_full_name: "acme/api".into(),
            }],
        };
        state.storage.insert_share_link(&link).await.unwrap();
        let req_id = RequestId::new();
        let req = domain::InvitationRequest {
            id: req_id,
            share_link_id: link.id,
            requester_id: 8,
            justification: None,
            state: domain::RequestState::Approved,
            decided_by: Some(7),
            decided_at: Some(dt("2026-05-04T13:00:00Z")),
            decline_reason: None,
            created_at: dt("2026-05-04T12:30:00Z"),
        };
        state
            .storage
            .insert_invitation_request_and_increment_uses(&req)
            .await
            .unwrap();
        let inv_id = GithubInvitationId::new();
        state
            .storage
            .insert_github_invitation(&DomainGithubInvitation {
                id: inv_id,
                invitation_request_id: req_id,
                repo_id: 10,
                github_invitation_id: Some(9988),
                state: InvitationState::Sent,
                error_message: None,
                created_at: dt("2026-05-04T13:00:00Z"),
                updated_at: dt("2026-05-04T13:00:00Z"),
            })
            .await
            .unwrap();
        (req_id, inv_id)
    }

    #[tokio::test]
    async fn cancel_calls_delete_and_marks_cancelled() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation {
                method: Method::Delete,
                url: "https://api.github.test/repos/acme/api/invitations/9988".into(),
                required_headers: BTreeMap::new(),
                expected_body: None,
                response: Response {
                    status: 204,
                    headers: BTreeMap::new(),
                    body: vec![],
                },
            },
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        cancel_logic(
            &state,
            &CancelInvitationInput {
                invitation_id: inv_id,
                installation_id: 9,
                by_user: Some(7),
                at: dt("2026-05-04T15:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state.storage.get_github_invitation(inv_id).await.unwrap().unwrap();
        assert_eq!(row.state, InvitationState::Cancelled);
    }

    #[tokio::test]
    async fn cancel_404_proceeds_to_mark_cancelled() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation::status(
                Method::Delete,
                "https://api.github.test/repos/acme/api/invitations/9988",
                404,
            ),
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        cancel_logic(
            &state,
            &CancelInvitationInput {
                invitation_id: inv_id,
                installation_id: 9,
                by_user: None,
                at: dt("2026-05-04T15:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state.storage.get_github_invitation(inv_id).await.unwrap().unwrap();
        assert_eq!(row.state, InvitationState::Cancelled);
    }

    #[tokio::test]
    async fn tick_expire_marks_expired_when_still_pending() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation::ok_json(
                Method::Get,
                "https://api.github.test/repos/acme/api/invitations?per_page=100",
                serde_json::json!([
                    {
                        "id": 9988,
                        "invitee": {"id": 42, "login": "alice"},
                        "permissions": "write",
                        "created_at": "2026-05-04T13:00:00Z"
                    }
                ]),
            ),
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        tick_expire_logic(
            &state,
            &TickExpireInput {
                invitation_id: inv_id,
                installation_id: 9,
                at: dt("2026-05-11T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state.storage.get_github_invitation(inv_id).await.unwrap().unwrap();
        assert_eq!(row.state, InvitationState::Expired);
    }

    #[tokio::test]
    async fn tick_expire_skips_when_no_longer_pending() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation::ok_json(
                Method::Get,
                "https://api.github.test/repos/acme/api/invitations?per_page=100",
                serde_json::json!([]),
            ),
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        tick_expire_logic(
            &state,
            &TickExpireInput {
                invitation_id: inv_id,
                installation_id: 9,
                at: dt("2026-05-11T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state.storage.get_github_invitation(inv_id).await.unwrap().unwrap();
        assert_eq!(row.state, InvitationState::Sent, "row left for webhook to settle");
    }
}
