//! `InvitationRequest` Workflow: submit the request, race admin decision against
//! timeout, dispatch to GithubInvitation on approval.

use crate::audit::{Actor, Target};
use crate::error::HandlerError;
use crate::impl_restate_json_payload;
use crate::state::AppState;
use audit::EventType;
use chrono::{DateTime, Duration, Utc};
// Aliased to avoid colliding with the `InvitationRequest` trait generated by
// `#[restate_sdk::workflow]` below. Task 16's pure-logic helpers insert
// `DomainInvitationRequest` rows; the alias lives here so the import set
// matches the established pattern (see `share_link.rs` / `github_invitation.rs`).
use domain::InvitationRequest as DomainInvitationRequest;
use domain::{RequestId, RequestState};
use restate_sdk::context::{
    ContextAwakeables, ContextClient, ContextSideEffects, ContextTimers, RunFuture,
    SharedWorkflowContext, WorkflowContext,
};
use restate_sdk::errors::TerminalError;
use serde::{Deserialize, Serialize};

/// Maximum time we keep a request "pending awaiting admin decision".
/// Per spec §Q8: `min(link.expires_at - now, 7d)`.
pub const MAX_DECISION_WAIT: Duration = Duration::days(7);

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SubmitRequestInput {
    pub request_id: RequestId,
    pub share_link_id: domain::ShareLinkId,
    pub requester_id: u64,
    pub justification: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// Decision payload — admin's approve/decline server function in Plan 5
/// resolves an awakeable with this.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub enum Decision {
    Approve {
        decided_by: u64,
        decided_at: DateTime<Utc>,
    },
    Decline {
        decided_by: u64,
        decided_at: DateTime<Utc>,
        reason: Option<String>,
    },
}

/// Final terminal state returned by the workflow. Wrapper newtype around
/// `domain::RequestState` because Restate framing traits (`Serialize`,
/// `Deserialize`, `PayloadMetadata`) can't be implemented for foreign types
/// (orphan rule); they have to live alongside the type definition.
#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
#[serde(transparent)]
pub struct SubmitOutput(pub RequestState);

impl_restate_json_payload!(SubmitRequestInput);
impl_restate_json_payload!(Decision);
impl_restate_json_payload!(SubmitOutput);
impl_restate_json_payload!(PreDecisionOutcome);
impl_restate_json_payload!(AppliedDecision);
impl_restate_json_payload!(DispatchInputs);

/// Wrapper around the per-repo `CreateInvitationInput` list so the workflow
/// can journal the fan-out plan via `ctx.run`. Restate's framing requires a
/// Sized type implementing its `Serialize`/`Deserialize`; `Vec<T>` from a
/// foreign-impl point of view doesn't satisfy that without a newtype.
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(transparent)]
pub struct DispatchInputs(pub Vec<crate::github_invitation::CreateInvitationInput>);

#[restate_sdk::workflow]
pub trait InvitationRequest {
    /// One-shot workflow per `request_id`. Returns the final state.
    async fn submit(input: SubmitRequestInput) -> std::result::Result<SubmitOutput, TerminalError>;

    /// Resolve the awakeable created in `submit` with an Approve/Decline decision.
    /// Called by the admin's server function (Plan 5).
    #[shared]
    async fn decide(decision: Decision) -> std::result::Result<(), TerminalError>;
}

pub struct InvitationRequestImpl {
    pub state: AppState,
}

impl InvitationRequest for InvitationRequestImpl {
    async fn submit(
        &self,
        ctx: WorkflowContext<'_>,
        input: SubmitRequestInput,
    ) -> std::result::Result<SubmitOutput, TerminalError> {
        let request_id = Some(ctx.invocation_id().to_string());

        // Phase 1: insert pending row, emit `request.created`, classify outcome.
        let outcome = {
            let state = self.state.clone();
            let input = input.clone();
            let request_id = request_id.clone();
            ctx.run(move || {
                let state = state.clone();
                let input = input.clone();
                let request_id = request_id.clone();
                async move {
                    pre_decision_logic(&state, &input, input.created_at, request_id)
                        .await
                        .map_err(crate::error::to_sdk_handler_error)
                }
            })
            .name("pre_decision")
            .await?
        };

        // Phase 2: pick the AppliedDecision that the apply step will record.
        // - AutoApprove: skip the awakeable race; stamp `at = input.created_at`.
        // - PendingDecision: race admin awakeable against the deadline timer.
        let applied: AppliedDecision = match outcome {
            PreDecisionOutcome::AutoApprove => AppliedDecision::AutoApprove {
                at: input.created_at,
            },
            PreDecisionOutcome::PendingDecision { decision_deadline } => {
                // The awakeable id is durably journaled the first time we hit
                // it; subsequent replays see the same id. Plan 5's admin
                // server function resolves it via Restate's HTTP API
                // (`/restate/awakeables/{id}/resolve`).
                let (_awakeable_id, promise) = ctx.awakeable::<Decision>();

                // ctx.sleep takes a Duration; our deadline is absolute. The
                // workflow handler runs at `created_at` (or replay time);
                // `created_at` is the most stable reference we have without
                // a fresh `ctx.run(|| now())`.
                let wait = decision_deadline - input.created_at;
                let wait = if wait <= Duration::zero() {
                    std::time::Duration::ZERO
                } else {
                    // chrono::Duration -> std::time::Duration; safe because we
                    // just bounded `wait` to >= 0 and `MAX_DECISION_WAIT` is days.
                    wait.to_std().unwrap_or(std::time::Duration::ZERO)
                };
                let sleep = ctx.sleep(wait);

                // The Restate SDK ships its own `select!` (DurableFuture-aware),
                // semantically the same as tokio's. Either branch yields an
                // `AppliedDecision` with `at = decision_deadline` (timer) or the
                // admin's `decided_at` (awakeable).
                restate_sdk::select! {
                    res = promise => {
                        match res? {
                            Decision::Approve { decided_by, decided_at } => AppliedDecision::Approve {
                                decided_by,
                                at: decided_at,
                            },
                            Decision::Decline { decided_by, decided_at, reason } => AppliedDecision::Decline {
                                decided_by,
                                at: decided_at,
                                reason,
                            },
                        }
                    },
                    _ = sleep => AppliedDecision::Expire {
                        at: decision_deadline,
                    },
                }
            }
        };

        // Phase 3: durably record the decision and emit the audit row.
        // Returning `SubmitOutput` (a local newtype) keeps the journal payload
        // Restate-serializable; `RequestState` lives in `domain` and we can't
        // implement `restate_sdk::serde::*` for foreign types.
        let SubmitOutput(final_state) = {
            let state = self.state.clone();
            let request_id_inner = request_id.clone();
            let req_id = input.request_id;
            let decision = applied.clone();
            ctx.run(move || {
                let state = state.clone();
                let request_id_inner = request_id_inner.clone();
                let decision = decision.clone();
                async move {
                    apply_decision_logic(&state, req_id, decision, request_id_inner)
                        .await
                        .map(SubmitOutput)
                        .map_err(crate::error::to_sdk_handler_error)
                }
            })
            .name("apply_decision")
            .await?
        };

        // Phase 4: on approval, fan out per-repo to GithubInvitation::create.
        if final_state == RequestState::Approved {
            // Build the per-repo dispatch inputs in a journaled run so each
            // GithubInvitationId is stable across replays.
            let DispatchInputs(inputs) = {
                let state = self.state.clone();
                let req_id = input.request_id;
                let now = input.created_at;
                ctx.run(move || {
                    let state = state.clone();
                    async move {
                        build_dispatch_inputs(&state, req_id, now)
                            .await
                            .map(DispatchInputs)
                            .map_err(crate::error::to_sdk_handler_error)
                    }
                })
                .name("build_dispatch_inputs")
                .await?
            };

            for inv_input in inputs {
                // Best-effort fan-out via the generated `GithubInvitationClient`.
                // Plan 5 / Task 19's `build_endpoint` will tie the actual
                // routing together; integration tests against a live Restate
                // are deferred to Plan 8.
                ctx.object_client::<crate::github_invitation::GithubInvitationClient>(
                    inv_input.invitation_id.to_string(),
                )
                .create(inv_input)
                .send();
            }
        }

        Ok(SubmitOutput(final_state))
    }

    async fn decide(
        &self,
        _ctx: SharedWorkflowContext<'_>,
        _decision: Decision,
    ) -> std::result::Result<(), TerminalError> {
        // Plan 5's admin server function resolves the awakeable directly via
        // Restate's HTTP API (`POST /restate/awakeables/{id}/resolve`), so
        // this shared handler is intentionally a no-op stub. Kept on the
        // trait so external callers that prefer the SDK shape compile; we
        // can wire it through `ctx.resolve_awakeable` later if needed.
        Ok(())
    }
}

/// Outcome of the pre-decision phase. Drives the workflow handler's branching.
///
/// `Serialize`/`Deserialize` derives + the `impl_restate_json_payload!` macro
/// below let this be journaled as the result of `ctx.run("pre_decision")`.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub enum PreDecisionOutcome {
    /// Link auto-approves; no awakeable race needed.
    AutoApprove,
    /// Pending admin decision; workflow must race awakeable vs. timeout.
    PendingDecision { decision_deadline: DateTime<Utc> },
}

/// Concrete decision the workflow has resolved on. Distinct from
/// [`Decision`] (the awakeable payload from admin) because the workflow may
/// also auto-approve or expire on its own.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub enum AppliedDecision {
    AutoApprove {
        at: DateTime<Utc>,
    },
    Approve {
        decided_by: u64,
        at: DateTime<Utc>,
    },
    Decline {
        decided_by: u64,
        at: DateTime<Utc>,
        reason: Option<String>,
    },
    Expire {
        at: DateTime<Utc>,
    },
}

/// Re-read share link, reject if not is_active, insert pending request,
/// emit `request.created`, return next-step instruction.
pub async fn pre_decision_logic(
    state: &AppState,
    input: &SubmitRequestInput,
    now: DateTime<Utc>,
    request_id: Option<String>,
) -> crate::error::Result<PreDecisionOutcome> {
    let link = state
        .storage
        .get_share_link_by_id(input.share_link_id)
        .await?
        .ok_or(HandlerError::Storage(storage::Error::NotFound))?;

    if !link.is_active(now) {
        return Err(HandlerError::Storage(storage::Error::NotFound));
    }

    let request = DomainInvitationRequest {
        id: input.request_id,
        share_link_id: input.share_link_id,
        requester_id: input.requester_id,
        justification: input.justification.clone(),
        state: RequestState::Pending,
        decided_by: None,
        decided_at: None,
        decline_reason: None,
        created_at: input.created_at,
    };
    state
        .storage
        .insert_invitation_request_and_increment_uses(&request)
        .await?;

    crate::audit::emit(
        state,
        link.account_id,
        EventType::RequestCreated,
        Actor::User(input.requester_id),
        Target::request(input.request_id),
        serde_json::json!({
            "share_link_id": input.share_link_id.to_string(),
            "auto_approve": !link.approval_required,
        }),
        request_id,
    )
    .await?;

    if !link.approval_required {
        return Ok(PreDecisionOutcome::AutoApprove);
    }

    let deadline = match link.expires_at {
        Some(e) => std::cmp::min(e, now + MAX_DECISION_WAIT),
        None => now + MAX_DECISION_WAIT,
    };
    Ok(PreDecisionOutcome::PendingDecision {
        decision_deadline: deadline,
    })
}

/// Apply an Approve/Decline/AutoApprove/Expire decision and emit the audit event.
/// Idempotent: a second call after the row is already terminal returns Ok.
pub async fn apply_decision_logic(
    state: &AppState,
    request_id: RequestId,
    decision: AppliedDecision,
    request_id_for_audit: Option<String>,
) -> crate::error::Result<RequestState> {
    let req = state
        .storage
        .get_invitation_request(request_id)
        .await?
        .ok_or(HandlerError::Storage(storage::Error::NotFound))?;
    if req.state.is_terminal() {
        return Ok(req.state);
    }

    let (new_state, decided_by, decided_at, decline_reason, event) = match &decision {
        AppliedDecision::Approve { decided_by, at } => (
            RequestState::Approved,
            *decided_by,
            *at,
            None,
            EventType::RequestApproved,
        ),
        AppliedDecision::AutoApprove { at } => (
            RequestState::Approved,
            req.requester_id, // auto-approve uses requester as decided_by per audit spec note
            *at,
            None,
            EventType::RequestApproved,
        ),
        AppliedDecision::Decline {
            decided_by,
            at,
            reason,
        } => (
            RequestState::Declined,
            *decided_by,
            *at,
            reason.clone(),
            EventType::RequestDeclined,
        ),
        AppliedDecision::Expire { at } => (
            RequestState::Expired,
            req.requester_id, // placeholder; system actor used in audit
            *at,
            None,
            EventType::RequestExpired,
        ),
    };

    match state
        .storage
        .record_request_decision(&storage::RequestDecision {
            request_id,
            state: new_state,
            decided_by,
            decided_at,
            decline_reason,
        })
        .await
    {
        Ok(()) => (),
        Err(storage::Error::NotFound) => return Ok(new_state), // already decided
        Err(e) => return Err(e.into()),
    }

    let link = state
        .storage
        .get_share_link_by_id(req.share_link_id)
        .await?
        .ok_or(HandlerError::Storage(storage::Error::NotFound))?;

    let actor = match decision {
        AppliedDecision::Approve { decided_by, .. }
        | AppliedDecision::Decline { decided_by, .. } => Actor::User(decided_by),
        AppliedDecision::AutoApprove { .. } | AppliedDecision::Expire { .. } => Actor::System,
    };
    crate::audit::emit(
        state,
        link.account_id,
        event,
        actor,
        Target::request(request_id),
        serde_json::json!({}),
        request_id_for_audit,
    )
    .await?;

    Ok(new_state)
}

/// Pure logic: read the request's share_link and build CreateInvitationInput
/// per repo. Emits no audit (each `GithubInvitation::create` is responsible
/// for its own).
pub async fn build_dispatch_inputs(
    state: &AppState,
    request_id: RequestId,
    now: DateTime<Utc>,
) -> crate::error::Result<Vec<crate::github_invitation::CreateInvitationInput>> {
    let req = state
        .storage
        .get_invitation_request(request_id)
        .await?
        .ok_or(HandlerError::Storage(storage::Error::NotFound))?;
    let link = state
        .storage
        .get_share_link_by_id(req.share_link_id)
        .await?
        .ok_or(HandlerError::Storage(storage::Error::NotFound))?;
    let recipient = state
        .storage
        .get_user(req.requester_id)
        .await?
        .ok_or(HandlerError::Storage(storage::Error::NotFound))?;

    Ok(link
        .repos
        .into_iter()
        .map(|r| crate::github_invitation::CreateInvitationInput {
            invitation_id: domain::GithubInvitationId::new(),
            invitation_request_id: request_id,
            installation_id: link.installation_id,
            repo_id: r.repo_id,
            repo_full_name: r.repo_full_name,
            recipient_login: recipient.login.clone(),
            permission: link.permission,
            now,
        })
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_support::{dt, fixture_state};
    use domain::{AccountType, Permission, SelectedRepos, ShareLink, ShareLinkId, Slug};
    use rand::SeedableRng;

    async fn seed_link(
        state: &AppState,
        approval_required: bool,
        expires_at: Option<DateTime<Utc>>,
    ) -> ShareLinkId {
        state
            .storage
            .insert_installation(&domain::Account {
                installation_id: 1,
                account_id: 100,
                account_login: "acme".into(),
                account_type: AccountType::Organization,
                installed_at: dt("2026-05-04T12:00:00Z"),
                uninstalled_at: None,
                selected_repos: SelectedRepos::All,
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&domain::User {
                user_id: 7,
                login: "creator".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&domain::User {
                user_id: 8,
                login: "alice".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        let link = ShareLink {
            id: ShareLinkId::new(),
            slug: Slug::generate(&mut rand_chacha::ChaCha8Rng::seed_from_u64(99)),
            installation_id: 1,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at,
            max_uses: None,
            uses_count: 0,
            permission: Permission::Pull,
            approval_required,
            internal_note: None,
            revoked_at: None,
            revoked_by: None,
            repos: vec![],
        };
        state.storage.insert_share_link(&link).await.unwrap();
        link.id
    }

    #[tokio::test]
    async fn pre_decision_auto_approve_when_link_doesnt_require() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, false, None).await;
        let req_id = RequestId::new();

        let outcome = pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                share_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();
        assert!(matches!(outcome, PreDecisionOutcome::AutoApprove));

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(req.state, RequestState::Pending); // pre-decision only inserts pending
    }

    #[tokio::test]
    async fn pre_decision_pending_with_deadline_capped_at_7d() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, None).await;

        let outcome = pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: RequestId::new(),
                share_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        match outcome {
            PreDecisionOutcome::PendingDecision { decision_deadline } => {
                assert_eq!(
                    decision_deadline,
                    dt("2026-05-04T12:30:00Z") + Duration::days(7)
                );
            }
            other => panic!("expected PendingDecision, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn pre_decision_pending_uses_link_expires_when_sooner() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, Some(dt("2026-05-06T12:00:00Z"))).await;

        let outcome = pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: RequestId::new(),
                share_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        match outcome {
            PreDecisionOutcome::PendingDecision { decision_deadline } => {
                assert_eq!(decision_deadline, dt("2026-05-06T12:00:00Z"));
            }
            other => panic!("expected PendingDecision, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn pre_decision_inactive_link_is_terminal() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, false, Some(dt("2026-05-03T00:00:00Z"))).await;

        let err = pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: RequestId::new(),
                share_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap_err();
        assert!(err.is_terminal());
    }

    #[tokio::test]
    async fn apply_decision_approve_records_and_audits() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, None).await;
        let req_id = RequestId::new();
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                share_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        let final_state = apply_decision_logic(
            &state,
            req_id,
            AppliedDecision::Approve {
                decided_by: 7,
                at: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();
        assert_eq!(final_state, RequestState::Approved);

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(req.state, RequestState::Approved);
        assert_eq!(req.decided_by, Some(7));
    }

    #[tokio::test]
    async fn apply_decision_decline_with_reason() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, None).await;
        let req_id = RequestId::new();
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                share_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        let final_state = apply_decision_logic(
            &state,
            req_id,
            AppliedDecision::Decline {
                decided_by: 7,
                at: dt("2026-05-04T13:00:00Z"),
                reason: Some("not familiar with this user".into()),
            },
            None,
        )
        .await
        .unwrap();
        assert_eq!(final_state, RequestState::Declined);

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(
            req.decline_reason.as_deref(),
            Some("not familiar with this user")
        );
    }

    #[tokio::test]
    async fn build_dispatch_inputs_emits_one_per_repo() {
        let state = fixture_state().await;
        // Seed installation + users (same fixture chain as `seed_link`).
        state
            .storage
            .insert_installation(&domain::Account {
                installation_id: 1,
                account_id: 100,
                account_login: "acme".into(),
                account_type: AccountType::Organization,
                installed_at: dt("2026-05-04T12:00:00Z"),
                uninstalled_at: None,
                selected_repos: SelectedRepos::All,
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&domain::User {
                user_id: 7,
                login: "creator".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&domain::User {
                user_id: 8,
                login: "alice".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();

        // Link with two repos so we can assert the fan-out shape.
        let link = ShareLink {
            id: ShareLinkId::new(),
            slug: Slug::generate(&mut rand_chacha::ChaCha8Rng::seed_from_u64(101)),
            installation_id: 1,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at: None,
            max_uses: None,
            uses_count: 0,
            permission: Permission::Push,
            approval_required: false, // auto-approve so the workflow path is exercised
            internal_note: None,
            revoked_at: None,
            revoked_by: None,
            repos: vec![
                domain::ShareLinkRepo {
                    repo_id: 10,
                    repo_full_name: "acme/api".into(),
                },
                domain::ShareLinkRepo {
                    repo_id: 11,
                    repo_full_name: "acme/web".into(),
                },
            ],
        };
        state.storage.insert_share_link(&link).await.unwrap();

        let req_id = RequestId::new();
        let now = dt("2026-05-04T12:30:00Z");
        let outcome = pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                share_link_id: link.id,
                requester_id: 8,
                justification: None,
                created_at: now,
            },
            now,
            None,
        )
        .await
        .unwrap();
        assert!(matches!(outcome, PreDecisionOutcome::AutoApprove));

        apply_decision_logic(
            &state,
            req_id,
            AppliedDecision::AutoApprove { at: now },
            None,
        )
        .await
        .unwrap();

        let inputs = build_dispatch_inputs(&state, req_id, now).await.unwrap();
        assert_eq!(inputs.len(), 2);
        // Both inputs should reference the same request, recipient, and
        // installation; the per-repo fields differ.
        for inp in &inputs {
            assert_eq!(inp.invitation_request_id, req_id);
            assert_eq!(inp.installation_id, 1);
            assert_eq!(inp.recipient_login, "alice");
            assert_eq!(inp.permission, Permission::Push);
            assert_eq!(inp.now, now);
        }
        let mut full_names: Vec<&str> = inputs.iter().map(|i| i.repo_full_name.as_str()).collect();
        full_names.sort();
        assert_eq!(full_names, vec!["acme/api", "acme/web"]);
        let mut repo_ids: Vec<u64> = inputs.iter().map(|i| i.repo_id).collect();
        repo_ids.sort();
        assert_eq!(repo_ids, vec![10, 11]);
    }

    #[tokio::test]
    async fn apply_decision_idempotent_after_first_decision() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, None).await;
        let req_id = RequestId::new();
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                share_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        apply_decision_logic(
            &state,
            req_id,
            AppliedDecision::Approve {
                decided_by: 7,
                at: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        // Second decision call returns the existing state, no re-audit.
        let result = apply_decision_logic(
            &state,
            req_id,
            AppliedDecision::Decline {
                decided_by: 7,
                at: dt("2026-05-04T14:00:00Z"),
                reason: Some("changed mind".into()),
            },
            None,
        )
        .await
        .unwrap();
        assert_eq!(result, RequestState::Approved, "first decision wins");
    }
}
