//! `InvitationRequest` Workflow: submit the request, race admin decision against
//! timeout, dispatch to GithubInvitation on approval.

use crate::impl_restate_json_payload;
use crate::state::AppState;
use chrono::{DateTime, Duration, Utc};
// Aliased to avoid colliding with the `InvitationRequest` trait generated by
// `#[restate_sdk::workflow]` below. Task 16's pure-logic helpers will insert
// `DomainInvitationRequest` rows; the alias lives here so the import set
// matches the established pattern (see `share_link.rs` / `github_invitation.rs`).
#[allow(unused_imports)]
use domain::InvitationRequest as DomainInvitationRequest;
use domain::{RequestId, RequestState};
use restate_sdk::context::{SharedWorkflowContext, WorkflowContext};
use restate_sdk::errors::TerminalError;
use serde::{Deserialize, Serialize};

/// Maximum time we keep a request "pending awaiting admin decision".
/// Per spec §Q8: `min(link.expires_at - now, 7d)`.
pub const MAX_DECISION_WAIT: Duration = Duration::days(7);

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct SubmitRequestInput {
    pub request_id: RequestId,
    pub share_link_id: domain::ShareLinkId,
    pub requester_id: u64,
    pub justification: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// Decision payload — admin's approve/decline server function in Plan 5
/// resolves an awakeable with this.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub enum Decision {
    Approve {
        decided_by: u64,
        decided_at: DateTime<Utc>,
    },
    Decline {
        decided_by: u64,
        decided_at: DateTime<Utc>,
        reason: Option<String>,
    },
}

/// Final terminal state returned by the workflow. Wrapper newtype around
/// `domain::RequestState` because Restate framing traits (`Serialize`,
/// `Deserialize`, `PayloadMetadata`) can't be implemented for foreign types
/// (orphan rule); they have to live alongside the type definition.
#[derive(Clone, Copy, Debug, Deserialize, Serialize)]
#[serde(transparent)]
pub struct SubmitOutput(pub RequestState);

impl_restate_json_payload!(SubmitRequestInput);
impl_restate_json_payload!(Decision);
impl_restate_json_payload!(SubmitOutput);

#[restate_sdk::workflow]
pub trait InvitationRequest {
    /// One-shot workflow per `request_id`. Returns the final state.
    async fn submit(input: SubmitRequestInput) -> std::result::Result<SubmitOutput, TerminalError>;

    /// Resolve the awakeable created in `submit` with an Approve/Decline decision.
    /// Called by the admin's server function (Plan 5).
    #[shared]
    async fn decide(decision: Decision) -> std::result::Result<(), TerminalError>;
}

pub struct InvitationRequestImpl {
    pub state: AppState,
}

impl InvitationRequest for InvitationRequestImpl {
    async fn submit(
        &self,
        _ctx: WorkflowContext<'_>,
        _input: SubmitRequestInput,
    ) -> std::result::Result<SubmitOutput, TerminalError> {
        unimplemented!("Task 17")
    }

    async fn decide(
        &self,
        _ctx: SharedWorkflowContext<'_>,
        _decision: Decision,
    ) -> std::result::Result<(), TerminalError> {
        unimplemented!("Task 17")
    }
}
