//! `InvitationLink` Virtual Object: create, revoke, tick_expiration.

use crate::audit::{Actor, Target};
use crate::state::AppState;
use audit::EventType;
use chrono::{DateTime, Utc};
// Aliased to avoid colliding with the `InvitationLink` trait generated by
// `#[restate_sdk::object]` below.
use domain::InvitationLink as DomainInvitationLink;
use domain::{InvitationLinkId, InvitationLinkRepo, Permission, Slug};
use rand::rngs::OsRng;
use restate_sdk::context::{ContextSideEffects, ObjectContext, RunFuture};
use restate_sdk::errors::TerminalError;
use restate_sdk::serde::Json;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct CreateLinkInput {
    pub installation_id: u64,
    pub account_id: u64,
    pub created_by: u64,
    pub created_at: DateTime<Utc>,
    pub expires_at: Option<DateTime<Utc>>,
    pub max_uses: Option<u32>,
    pub permission: Permission,
    pub approval_required: bool,
    pub description: String,
    pub internal_note: Option<String>,
    pub repos: Vec<InvitationLinkRepo>,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct CreateLinkOutput {
    pub link_id: InvitationLinkId,
    pub slug: String,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct RevokeLinkInput {
    pub link_id: InvitationLinkId,
    pub by_user: u64,
    pub when: DateTime<Utc>,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct TickExpirationInput {
    pub link_id: InvitationLinkId,
    pub at: DateTime<Utc>,
}

#[restate_sdk::object]
pub trait InvitationLink {
    async fn create(
        input: Json<CreateLinkInput>,
    ) -> std::result::Result<Json<CreateLinkOutput>, TerminalError>;
    async fn revoke(input: Json<RevokeLinkInput>) -> std::result::Result<(), TerminalError>;
    async fn tick_expiration(
        input: Json<TickExpirationInput>,
    ) -> std::result::Result<(), TerminalError>;
}

pub struct InvitationLinkImpl {
    pub state: AppState,
}

impl InvitationLink for InvitationLinkImpl {
    async fn create(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<CreateLinkInput>,
    ) -> std::result::Result<Json<CreateLinkOutput>, TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        let Json(output) = ctx
            .run(|| async {
                create_logic(&self.state, &input, request_id.clone())
                    .await
                    .map(Json)
                    .map_err(crate::error::to_sdk_handler_error)
            })
            .name("create")
            .await?;
        Ok(Json(output))
    }

    async fn revoke(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<RevokeLinkInput>,
    ) -> std::result::Result<(), TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            revoke_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("revoke")
        .await
    }

    async fn tick_expiration(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<TickExpirationInput>,
    ) -> std::result::Result<(), TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            tick_expiration_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("tick_expiration")
        .await
    }
}

/// Pure logic: generate a slug, write the link + repos rows, emit audit.
pub async fn create_logic(
    state: &AppState,
    input: &CreateLinkInput,
    request_id: Option<String>,
) -> crate::error::Result<CreateLinkOutput> {
    create_invitation_link_transition(state, input, request_id).await
}

async fn create_invitation_link_transition(
    state: &AppState,
    input: &CreateLinkInput,
    request_id: Option<String>,
) -> crate::error::Result<CreateLinkOutput> {
    let mut rng = OsRng;
    let slug = Slug::generate(&mut rng);
    let link_id = InvitationLinkId::new();

    let link = DomainInvitationLink {
        id: link_id,
        slug: slug.clone(),
        installation_id: input.installation_id,
        account_id: input.account_id,
        created_by: input.created_by,
        created_at: input.created_at,
        expires_at: input.expires_at,
        max_uses: input.max_uses,
        uses_count: 0,
        permission: input.permission,
        approval_required: input.approval_required,
        description: input.description.clone(),
        internal_note: input.internal_note.clone(),
        revoked_at: None,
        revoked_by: None,
        repos: input.repos.clone(),
    };

    state.storage.insert_invitation_link(&link).await?;

    crate::audit::emit(
        state,
        input.account_id,
        EventType::InvitationLinkCreated,
        Actor::User(input.created_by),
        Target::invitation_link(link_id),
        serde_json::json!({
            "permission": input.permission.to_string(),
            "approval_required": input.approval_required,
            "max_uses": input.max_uses,
            "repo_count": input.repos.len(),
        }),
        request_id,
    )
    .await?;

    Ok(CreateLinkOutput {
        link_id,
        slug: slug.as_str().to_string(),
    })
}

/// Pure logic: stamp `revoked_at`/`revoked_by`; emit audit. Idempotent on
/// double-revoke (storage returns NotFound when no-op; we treat as Ok).
pub async fn revoke_logic(
    state: &AppState,
    input: &RevokeLinkInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    revoke_invitation_link_transition(state, input, request_id).await
}

async fn revoke_invitation_link_transition(
    state: &AppState,
    input: &RevokeLinkInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    match state
        .storage
        .mark_invitation_link_revoked(input.link_id, input.by_user, input.when)
        .await
    {
        Ok(()) => (),
        Err(storage::Error::NotFound) => return Ok(()),
        Err(e) => return Err(e.into()),
    }

    let link = state
        .storage
        .get_invitation_link_by_id(input.link_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(
            storage::Error::NotFound,
        ))?;

    crate::audit::emit(
        state,
        link.account_id,
        EventType::InvitationLinkRevoked,
        Actor::User(input.by_user),
        Target::invitation_link(input.link_id),
        serde_json::json!({"by_user": input.by_user}),
        request_id,
    )
    .await
}

/// Pure logic: if the link is past its expiry and not already revoked, emit
/// `invitation_link.expired`. No state mutation — `is_active(now)` already reflects
/// the expiry. Idempotent under repeated calls.
pub async fn tick_expiration_logic(
    state: &AppState,
    input: &TickExpirationInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    expire_invitation_link_transition(state, input, request_id).await
}

async fn expire_invitation_link_transition(
    state: &AppState,
    input: &TickExpirationInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    let link = state
        .storage
        .get_invitation_link_by_id(input.link_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(
            storage::Error::NotFound,
        ))?;

    if link.revoked_at.is_some() {
        return Ok(());
    }
    let Some(expires) = link.expires_at else {
        return Err(crate::error::HandlerError::Invariant(format!(
            "tick_expiration fired for link {} which has no expires_at",
            input.link_id
        )));
    };
    if input.at < expires {
        return Ok(());
    }

    crate::audit::emit(
        state,
        link.account_id,
        EventType::InvitationLinkExpired,
        Actor::System,
        Target::invitation_link(input.link_id),
        serde_json::json!({"expired_at": input.at.to_rfc3339()}),
        request_id,
    )
    .await
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::HandlerError;
    use crate::test_support::{dt, fixture_state, fixture_state_with_storage};
    use ::audit::{ActorKind, EventType, TargetKind};
    use domain::{AccountType, SelectedRepos};

    async fn seed_installation_and_user(state: &AppState) {
        let acct = domain::Account {
            installation_id: 1,
            account_id: 100,
            account_login: "acme".into(),
            account_type: AccountType::Organization,
            installed_at: dt("2026-05-04T12:00:00Z"),
            uninstalled_at: None,
            selected_repos: SelectedRepos::All,
        };
        state.storage.insert_installation(&acct).await.unwrap();
        let user = domain::User {
            user_id: 7,
            login: "creator".into(),
            avatar_url: None,
            last_seen_at: dt("2026-05-04T12:00:00Z"),
        };
        state.storage.upsert_user(&user).await.unwrap();
    }

    fn sample_input() -> CreateLinkInput {
        CreateLinkInput {
            installation_id: 1,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at: Some(dt("2026-06-03T12:00:00Z")),
            max_uses: Some(5),
            permission: Permission::Pull,
            approval_required: true,
            description: "AI coding workshop".into(),
            internal_note: Some("test".into()),
            repos: vec![InvitationLinkRepo {
                repo_id: 10,
                repo_full_name: "acme/api".into(),
            }],
        }
    }

    async fn audit_events(
        storage: &::storage::SqlxStorage,
        account_id: u64,
    ) -> Vec<::audit::AuditEvent> {
        storage.debug_list_audit(account_id).await.unwrap()
    }

    #[tokio::test]
    async fn create_inserts_link_with_generated_slug() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;

        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        assert_eq!(out.slug.len(), 16);

        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.slug.as_str(), out.slug);
        assert_eq!(link.repos.len(), 1);
        assert_eq!(link.repos[0].repo_full_name, "acme/api");
        assert_eq!(link.uses_count, 0);
        assert_eq!(link.permission, Permission::Pull);
        assert!(link.approval_required);
        assert_eq!(link.description, "AI coding workshop");
    }

    #[tokio::test]
    async fn create_transition_inserts_link_and_audits() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;

        let out =
            create_invitation_link_transition(&state, &sample_input(), Some("req-create".into()))
                .await
                .unwrap();

        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.slug.as_str(), out.slug);
        assert_eq!(link.repos.len(), 1);

        let audits = audit_events(&storage, 100).await;
        assert_eq!(audits.len(), 1);
        let event = &audits[0];
        assert_eq!(event.event_type, EventType::InvitationLinkCreated);
        assert_eq!(event.actor_kind, ActorKind::User);
        assert_eq!(event.actor_id, Some(7));
        assert_eq!(event.target_kind, TargetKind::InvitationLink);
        assert_eq!(event.target_id, out.link_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-create"));
        assert_eq!(
            event.metadata.get("permission"),
            Some(&serde_json::json!("pull"))
        );
        assert_eq!(
            event.metadata.get("approval_required"),
            Some(&serde_json::json!(true))
        );
        assert_eq!(event.metadata.get("max_uses"), Some(&serde_json::json!(5)));
        assert_eq!(
            event.metadata.get("repo_count"),
            Some(&serde_json::json!(1))
        );
        assert_eq!(link.description, "AI coding workshop");
        assert!(event.metadata.get("description").is_none());
    }

    #[tokio::test]
    async fn create_unknown_installation_is_terminal() {
        let state = fixture_state().await;
        let mut input = sample_input();
        input.installation_id = 999;
        let err = create_logic(&state, &input, None).await.unwrap_err();
        assert!(err.is_terminal());
    }

    #[tokio::test]
    async fn create_no_repos_is_allowed() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;

        let mut input = sample_input();
        input.repos.clear();
        let out = create_logic(&state, &input, None).await.unwrap();
        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert!(link.repos.is_empty());
    }

    #[tokio::test]
    async fn revoke_marks_and_audits() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();

        revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.revoked_by, Some(7));
        assert!(link.revoked_at.is_some());
    }

    #[tokio::test]
    async fn revoke_transition_marks_and_audits_once() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out =
            create_invitation_link_transition(&state, &sample_input(), Some("req-create".into()))
                .await
                .unwrap();

        revoke_invitation_link_transition(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            Some("req-revoke".into()),
        )
        .await
        .unwrap();

        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.revoked_by, Some(7));
        assert_eq!(link.revoked_at, Some(dt("2026-05-04T13:00:00Z")));

        revoke_invitation_link_transition(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T14:00:00Z"),
            },
            Some("req-revoke-again".into()),
        )
        .await
        .unwrap();

        let audits = audit_events(&storage, 100).await;
        let revoked: Vec<_> = audits
            .iter()
            .filter(|event| event.event_type == EventType::InvitationLinkRevoked)
            .collect();
        assert_eq!(revoked.len(), 1);
        let event = revoked[0];
        assert_eq!(event.actor_kind, ActorKind::User);
        assert_eq!(event.actor_id, Some(7));
        assert_eq!(event.target_kind, TargetKind::InvitationLink);
        assert_eq!(event.target_id, out.link_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-revoke"));
        assert_eq!(event.metadata.get("by_user"), Some(&serde_json::json!(7)));
    }

    #[tokio::test]
    async fn revoke_already_revoked_is_idempotent() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();

        revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        // Second revoke on already-revoked link.
        let result = revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T14:00:00Z"),
            },
            None,
        )
        .await;
        assert!(
            result.is_ok(),
            "double-revoke should be idempotent: {result:?}"
        );
    }

    #[tokio::test]
    async fn tick_expiration_emits_when_past_expiry() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();

        tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2026-06-03T12:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();
    }

    #[tokio::test]
    async fn expire_transition_emits_audit_without_state_mutation() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out =
            create_invitation_link_transition(&state, &sample_input(), Some("req-create".into()))
                .await
                .unwrap();
        let expired_at = dt("2026-06-03T12:00:00Z");

        expire_invitation_link_transition(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: expired_at,
            },
            Some("req-expire".into()),
        )
        .await
        .unwrap();

        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert!(link.revoked_at.is_none());
        assert_eq!(link.uses_count, 0);
        assert!(!link.is_active(expired_at));

        let audits = audit_events(&storage, 100).await;
        let event = audits
            .iter()
            .find(|event| event.event_type == EventType::InvitationLinkExpired)
            .expect("expiration should emit audit event");
        assert_eq!(event.actor_kind, ActorKind::System);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::InvitationLink);
        assert_eq!(event.target_id, out.link_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-expire"));
        assert_eq!(
            event.metadata.get("expired_at"),
            Some(&serde_json::json!(expired_at.to_rfc3339()))
        );
    }

    #[tokio::test]
    async fn tick_expiration_skips_revoked_link() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2026-06-03T12:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();
    }

    #[tokio::test]
    async fn expire_transition_skips_early_and_revoked_links_without_audit() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out =
            create_invitation_link_transition(&state, &sample_input(), Some("req-create".into()))
                .await
                .unwrap();

        expire_invitation_link_transition(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2026-06-03T11:59:59Z"),
            },
            Some("req-early".into()),
        )
        .await
        .unwrap();

        revoke_invitation_link_transition(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            Some("req-revoke".into()),
        )
        .await
        .unwrap();

        expire_invitation_link_transition(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2026-06-03T12:00:00Z"),
            },
            Some("req-expire-revoked".into()),
        )
        .await
        .unwrap();

        let audits = audit_events(&storage, 100).await;
        let expired_count = audits
            .iter()
            .filter(|event| event.event_type == EventType::InvitationLinkExpired)
            .count();
        assert_eq!(expired_count, 0);
    }

    #[tokio::test]
    async fn tick_expiration_unknown_link_is_terminal() {
        let state = fixture_state().await;
        let err = tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: InvitationLinkId::new(),
                at: dt("2026-06-03T12:00:00Z"),
            },
            None,
        )
        .await
        .unwrap_err();
        assert!(err.is_terminal());
    }

    #[tokio::test]
    async fn tick_expiration_no_expires_at_is_terminal_invariant() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;

        let mut no_expiry = sample_input();
        no_expiry.expires_at = None;
        let out = create_logic(&state, &no_expiry, None).await.unwrap();

        let err = tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2099-01-01T00:00:00Z"),
            },
            None,
        )
        .await
        .unwrap_err();
        assert!(matches!(err, HandlerError::Invariant(_)));
        assert!(err.is_terminal());
    }
}
