//! `ShareLink` Virtual Object: create, revoke, tick_expiration.

use crate::audit::{Actor, Target};
use crate::impl_restate_json_payload;
use crate::state::AppState;
use audit::EventType;
use chrono::{DateTime, Utc};
// Aliased to avoid colliding with the `ShareLink` trait generated by
// `#[restate_sdk::object]` below.
use domain::ShareLink as DomainShareLink;
use domain::{Permission, ShareLinkId, ShareLinkRepo, Slug};
use rand::rngs::OsRng;
use restate_sdk::context::{ContextSideEffects, ObjectContext, RunFuture};
use restate_sdk::errors::TerminalError;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CreateLinkInput {
    pub installation_id: u64,
    pub account_id: u64,
    pub created_by: u64,
    pub created_at: DateTime<Utc>,
    pub expires_at: Option<DateTime<Utc>>,
    pub max_uses: Option<u32>,
    pub permission: Permission,
    pub approval_required: bool,
    pub internal_note: Option<String>,
    pub repos: Vec<ShareLinkRepo>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CreateLinkOutput {
    pub link_id: ShareLinkId,
    pub slug: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct RevokeLinkInput {
    pub link_id: ShareLinkId,
    pub by_user: u64,
    pub when: DateTime<Utc>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TickExpirationInput {
    pub link_id: ShareLinkId,
    pub at: DateTime<Utc>,
}

impl_restate_json_payload!(CreateLinkInput);
impl_restate_json_payload!(CreateLinkOutput);
impl_restate_json_payload!(RevokeLinkInput);
impl_restate_json_payload!(TickExpirationInput);

#[restate_sdk::object]
pub trait ShareLink {
    async fn create(input: CreateLinkInput)
    -> std::result::Result<CreateLinkOutput, TerminalError>;
    async fn revoke(input: RevokeLinkInput) -> std::result::Result<(), TerminalError>;
    async fn tick_expiration(input: TickExpirationInput) -> std::result::Result<(), TerminalError>;
}

pub struct ShareLinkImpl {
    pub state: AppState,
}

impl ShareLink for ShareLinkImpl {
    async fn create(
        &self,
        ctx: ObjectContext<'_>,
        input: CreateLinkInput,
    ) -> std::result::Result<CreateLinkOutput, TerminalError> {
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            create_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("create")
        .await
    }

    async fn revoke(
        &self,
        ctx: ObjectContext<'_>,
        input: RevokeLinkInput,
    ) -> std::result::Result<(), TerminalError> {
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            revoke_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("revoke")
        .await
    }

    async fn tick_expiration(
        &self,
        ctx: ObjectContext<'_>,
        input: TickExpirationInput,
    ) -> std::result::Result<(), TerminalError> {
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            tick_expiration_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("tick_expiration")
        .await
    }
}

/// Pure logic: generate a slug, write the link + repos rows, emit audit.
pub async fn create_logic(
    state: &AppState,
    input: &CreateLinkInput,
    request_id: Option<String>,
) -> crate::error::Result<CreateLinkOutput> {
    let mut rng = OsRng;
    let slug = Slug::generate(&mut rng);
    let link_id = ShareLinkId::new();

    let link = DomainShareLink {
        id: link_id,
        slug: slug.clone(),
        installation_id: input.installation_id,
        account_id: input.account_id,
        created_by: input.created_by,
        created_at: input.created_at,
        expires_at: input.expires_at,
        max_uses: input.max_uses,
        uses_count: 0,
        permission: input.permission,
        approval_required: input.approval_required,
        internal_note: input.internal_note.clone(),
        revoked_at: None,
        revoked_by: None,
        repos: input.repos.clone(),
    };

    state.storage.insert_share_link(&link).await?;

    crate::audit::emit(
        state,
        input.account_id,
        EventType::ShareLinkCreated,
        Actor::User(input.created_by),
        Target::share_link(link_id),
        serde_json::json!({
            "permission": input.permission.to_string(),
            "approval_required": input.approval_required,
            "max_uses": input.max_uses,
            "repo_count": input.repos.len(),
        }),
        request_id,
    )
    .await?;

    Ok(CreateLinkOutput {
        link_id,
        slug: slug.as_str().to_string(),
    })
}

/// Pure logic: stamp `revoked_at`/`revoked_by`; emit audit. Idempotent on
/// double-revoke (storage returns NotFound when no-op; we treat as Ok).
pub async fn revoke_logic(
    state: &AppState,
    input: &RevokeLinkInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    match state
        .storage
        .mark_share_link_revoked(input.link_id, input.by_user, input.when)
        .await
    {
        Ok(()) => (),
        Err(storage::Error::NotFound) => return Ok(()), // idempotent
        Err(e) => return Err(e.into()),
    }

    let link = state
        .storage
        .get_share_link_by_id(input.link_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(
            storage::Error::NotFound,
        ))?;

    let metadata = serde_json::json!({"by_user": input.by_user});
    crate::audit::emit(
        state,
        link.account_id,
        EventType::ShareLinkRevoked,
        Actor::User(input.by_user),
        Target::share_link(input.link_id),
        metadata,
        request_id,
    )
    .await
}

/// Pure logic: if the link is past its expiry and not already revoked, emit
/// `share_link.expired`. No state mutation — `is_active(now)` already reflects
/// the expiry. Idempotent under repeated calls.
pub async fn tick_expiration_logic(
    state: &AppState,
    input: &TickExpirationInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    let link = state
        .storage
        .get_share_link_by_id(input.link_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(
            storage::Error::NotFound,
        ))?;

    // Defensive: an admin may have revoked the link before the timer fired.
    if link.revoked_at.is_some() {
        return Ok(());
    }
    let Some(expires) = link.expires_at else {
        return Err(crate::error::HandlerError::Invariant(format!(
            "tick_expiration fired for link {} which has no expires_at",
            input.link_id
        )));
    };
    if input.at < expires {
        // Timer fired early; skip.
        return Ok(());
    }

    let metadata = serde_json::json!({"expired_at": input.at.to_rfc3339()});
    crate::audit::emit(
        state,
        link.account_id,
        EventType::ShareLinkExpired,
        Actor::System,
        Target::share_link(input.link_id),
        metadata,
        request_id,
    )
    .await
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::HandlerError;
    use crate::test_support::{dt, fixture_state};
    use domain::{AccountType, SelectedRepos};

    async fn seed_installation_and_user(state: &AppState) {
        let acct = domain::Account {
            installation_id: 1,
            account_id: 100,
            account_login: "acme".into(),
            account_type: AccountType::Organization,
            installed_at: dt("2026-05-04T12:00:00Z"),
            uninstalled_at: None,
            selected_repos: SelectedRepos::All,
        };
        state.storage.insert_installation(&acct).await.unwrap();
        let user = domain::User {
            user_id: 7,
            login: "creator".into(),
            avatar_url: None,
            last_seen_at: dt("2026-05-04T12:00:00Z"),
        };
        state.storage.upsert_user(&user).await.unwrap();
    }

    fn sample_input() -> CreateLinkInput {
        CreateLinkInput {
            installation_id: 1,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at: Some(dt("2026-06-03T12:00:00Z")),
            max_uses: Some(5),
            permission: Permission::Pull,
            approval_required: true,
            internal_note: Some("test".into()),
            repos: vec![ShareLinkRepo {
                repo_id: 10,
                repo_full_name: "acme/api".into(),
            }],
        }
    }

    #[tokio::test]
    async fn create_inserts_link_with_generated_slug() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;

        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        assert_eq!(out.slug.len(), 16);

        let link = state
            .storage
            .get_share_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.slug.as_str(), out.slug);
        assert_eq!(link.repos.len(), 1);
        assert_eq!(link.repos[0].repo_full_name, "acme/api");
        assert_eq!(link.uses_count, 0);
        assert_eq!(link.permission, Permission::Pull);
        assert!(link.approval_required);
    }

    #[tokio::test]
    async fn create_unknown_installation_is_terminal() {
        let state = fixture_state().await;
        let mut input = sample_input();
        input.installation_id = 999;
        let err = create_logic(&state, &input, None).await.unwrap_err();
        assert!(err.is_terminal());
    }

    #[tokio::test]
    async fn create_no_repos_is_allowed() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;

        let mut input = sample_input();
        input.repos.clear();
        let out = create_logic(&state, &input, None).await.unwrap();
        let link = state
            .storage
            .get_share_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert!(link.repos.is_empty());
    }

    #[tokio::test]
    async fn revoke_marks_and_audits() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();

        revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let link = state
            .storage
            .get_share_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.revoked_by, Some(7));
        assert!(link.revoked_at.is_some());
    }

    #[tokio::test]
    async fn revoke_already_revoked_is_idempotent() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();

        revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        // Second revoke on already-revoked link.
        let result = revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T14:00:00Z"),
            },
            None,
        )
        .await;
        assert!(
            result.is_ok(),
            "double-revoke should be idempotent: {result:?}"
        );
    }

    #[tokio::test]
    async fn tick_expiration_emits_when_past_expiry() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();

        tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2026-06-03T12:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();
    }

    #[tokio::test]
    async fn tick_expiration_skips_revoked_link() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2026-06-03T12:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();
    }

    #[tokio::test]
    async fn tick_expiration_unknown_link_is_terminal() {
        let state = fixture_state().await;
        let err = tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: ShareLinkId::new(),
                at: dt("2026-06-03T12:00:00Z"),
            },
            None,
        )
        .await
        .unwrap_err();
        assert!(err.is_terminal());
    }

    #[tokio::test]
    async fn tick_expiration_no_expires_at_is_terminal_invariant() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;

        let mut no_expiry = sample_input();
        no_expiry.expires_at = None;
        let out = create_logic(&state, &no_expiry, None).await.unwrap();

        let err = tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2099-01-01T00:00:00Z"),
            },
            None,
        )
        .await
        .unwrap_err();
        assert!(matches!(err, HandlerError::Invariant(_)));
        assert!(err.is_terminal());
    }
}
