//! `ShareLink` Virtual Object: create, revoke, tick_expiration.

// Tasks 8–10 fill in the methods that use these.
#![allow(unused_imports)]

use crate::audit::{Actor, Target};
use crate::error::HandlerError;
use crate::impl_restate_json_payload;
use crate::state::AppState;
use audit::EventType;
use chrono::{DateTime, Utc};
// Aliased to avoid colliding with the `ShareLink` trait generated by
// `#[restate_sdk::object]` below.
use domain::ShareLink as DomainShareLink;
use domain::{Permission, ShareLinkId, ShareLinkRepo, Slug};
use rand::SeedableRng;
use rand::rngs::OsRng;
use restate_sdk::context::{ContextSideEffects, ObjectContext, RunFuture};
use restate_sdk::errors::TerminalError;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CreateLinkInput {
    pub installation_id: u64,
    pub account_id: u64,
    pub created_by: u64,
    pub created_at: DateTime<Utc>,
    pub expires_at: Option<DateTime<Utc>>,
    pub max_uses: Option<u32>,
    pub permission: Permission,
    pub approval_required: bool,
    pub internal_note: Option<String>,
    pub repos: Vec<ShareLinkRepo>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CreateLinkOutput {
    pub link_id: ShareLinkId,
    pub slug: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct RevokeLinkInput {
    pub link_id: ShareLinkId,
    pub by_user: u64,
    pub when: DateTime<Utc>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct TickExpirationInput {
    pub link_id: ShareLinkId,
    pub at: DateTime<Utc>,
}

impl_restate_json_payload!(CreateLinkInput);
impl_restate_json_payload!(CreateLinkOutput);
impl_restate_json_payload!(RevokeLinkInput);
impl_restate_json_payload!(TickExpirationInput);

#[restate_sdk::object]
pub trait ShareLink {
    async fn create(input: CreateLinkInput) -> std::result::Result<CreateLinkOutput, TerminalError>;
    async fn revoke(input: RevokeLinkInput) -> std::result::Result<(), TerminalError>;
    async fn tick_expiration(input: TickExpirationInput) -> std::result::Result<(), TerminalError>;
}

pub struct ShareLinkImpl {
    pub state: AppState,
}

impl ShareLink for ShareLinkImpl {
    async fn create(
        &self,
        _ctx: ObjectContext<'_>,
        _input: CreateLinkInput,
    ) -> std::result::Result<CreateLinkOutput, TerminalError> {
        unimplemented!("Task 8")
    }

    async fn revoke(
        &self,
        _ctx: ObjectContext<'_>,
        _input: RevokeLinkInput,
    ) -> std::result::Result<(), TerminalError> {
        unimplemented!("Task 9")
    }

    async fn tick_expiration(
        &self,
        _ctx: ObjectContext<'_>,
        _input: TickExpirationInput,
    ) -> std::result::Result<(), TerminalError> {
        unimplemented!("Task 10")
    }
}
