//! `GithubInvitation` Virtual Object: create, on_webhook, cancel, tick_expire.

use crate::audit::{Actor, Target};
use crate::state::AppState;
use chrono::{DateTime, Utc};
use ghinvite_core::audit::EventType;
// Aliased to avoid colliding with the `GithubInvitation` trait generated by
// `#[restate_sdk::object]` below.
use ghinvite_core::GithubInvitation as DomainGithubInvitation;
use ghinvite_core::{GithubInvitationId, InvitationState, RepositoryIdentity, RequestId};
use restate_sdk::context::{ContextClient, ContextSideEffects, ObjectContext, RunFuture};
use restate_sdk::errors::TerminalError;
use restate_sdk::serde::Json;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct CreateInvitationInput {
    pub invitation_id: GithubInvitationId,
    pub invitation_request_id: RequestId,
    pub installation_id: u64,
    pub repo_id: u64,
    pub repo_full_name: String, // "owner/name"
    pub recipient_login: String,
    pub permission: ghinvite_core::Permission,
    pub now: DateTime<Utc>,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct OnWebhookInput {
    pub invitation_id: GithubInvitationId,
    pub action: WebhookAction,
    pub at: DateTime<Utc>,
}

#[derive(Clone, Copy, Debug, Deserialize, JsonSchema, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum WebhookAction {
    Accepted,
    Declined,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct CancelInvitationInput {
    pub invitation_id: GithubInvitationId,
    pub installation_id: u64,
    pub by_user: Option<u64>, // None when system-cancelled (cascade in v2)
    pub at: DateTime<Utc>,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct TickExpireInput {
    pub invitation_id: GithubInvitationId,
    pub installation_id: u64,
    pub at: DateTime<Utc>,
}

fn repository_identity(full_name: &str) -> crate::error::Result<RepositoryIdentity> {
    RepositoryIdentity::parse(full_name.to_owned()).map_err(|err| {
        crate::error::HandlerError::Invariant(format!(
            "invalid repo_full_name {full_name:?}: {err}"
        ))
    })
}

#[restate_sdk::object]
pub trait GithubInvitation {
    async fn reconcile_v1(
        input: Json<crate::settlement_v1::ReconcileEvidence>,
    ) -> std::result::Result<(), TerminalError>;
    async fn on_webhook_v1(input: Json<OnWebhookInput>) -> std::result::Result<(), TerminalError>;
    async fn cancel_v1(
        input: Json<CancelInvitationInput>,
    ) -> std::result::Result<(), TerminalError>;
    async fn tick_expire_v1(input: Json<TickExpireInput>)
    -> std::result::Result<(), TerminalError>;
    async fn create(input: Json<CreateInvitationInput>) -> std::result::Result<(), TerminalError>;
    async fn on_webhook(input: Json<OnWebhookInput>) -> std::result::Result<(), TerminalError>;
    async fn cancel(input: Json<CancelInvitationInput>) -> std::result::Result<(), TerminalError>;
    async fn tick_expire(input: Json<TickExpireInput>) -> std::result::Result<(), TerminalError>;
}

pub struct GithubInvitationImpl {
    pub state: AppState,
}

impl GithubInvitation for GithubInvitationImpl {
    async fn reconcile_v1(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<crate::settlement_v1::ReconcileEvidence>,
    ) -> std::result::Result<(), TerminalError> {
        crate::settlement_v1::reconcile(&self.state, ctx, input).await
    }
    async fn on_webhook_v1(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<OnWebhookInput>,
    ) -> std::result::Result<(), TerminalError> {
        crate::settlement_v1::webhook(&self.state, ctx, input).await
    }
    async fn cancel_v1(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<CancelInvitationInput>,
    ) -> std::result::Result<(), TerminalError> {
        crate::settlement_v1::cancel(&self.state, ctx, input).await
    }
    async fn tick_expire_v1(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<TickExpireInput>,
    ) -> std::result::Result<(), TerminalError> {
        crate::settlement_v1::expire(&self.state, ctx, input).await
    }
    async fn create(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<CreateInvitationInput>,
    ) -> std::result::Result<(), TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        let Json(throttled_for_secs) = ctx
            .run(|| async {
                create_logic(&self.state, &input, request_id.clone())
                    .await
                    .map(Json)
                    .map_err(crate::error::to_sdk_handler_error)
            })
            .name("create")
            .await?;
        if let Some(secs) = throttled_for_secs {
            // Waiting here would hold this invitation's object lock for the
            // whole rate-limit window, blocking its webhook, cancel, and expiry
            // handlers. A durable continuation releases the lock and re-enters
            // the same idempotent attempt once the limit has had time to clear.
            ctx.object_client::<GithubInvitationClient>(ctx.key())
                .create(Json(input))
                .send_after(std::time::Duration::from_secs(secs))
                .await?;
        }
        Ok(())
    }

    async fn on_webhook(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<OnWebhookInput>,
    ) -> std::result::Result<(), TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            on_webhook_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("on_webhook")
        .await
    }

    async fn cancel(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<CancelInvitationInput>,
    ) -> std::result::Result<(), TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            cancel_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("cancel")
        .await
    }

    async fn tick_expire(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<TickExpireInput>,
    ) -> std::result::Result<(), TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            tick_expire_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("tick_expire")
        .await
    }
}

/// Pure logic: row-insert in `Sending`, call GitHub, branch on status, update
/// row + audit. Returns `Ok(None)` for both 201 (sent) and 204 (already a
/// collaborator) paths. Terminal 4xx is recorded as Failed and returns Ok so
/// Restate does NOT retry. Transient 5xx returns Err to trigger Restate retry.
///
/// A throttled response is neither: it records nothing, leaves the row in
/// `Sending`, and returns `Ok(Some(seconds))` so the caller can re-attempt
/// after that bounded wait. A rate limit is GitHub declining to answer, so
/// presenting it as a definitive send failure would be a lie about the
/// invitation.
///
/// The `Option<u64>` is journaled by the caller's `ctx.run`; a `null` left by
/// an older `()`-returning journal still reads back as `None`.
pub async fn create_logic(
    state: &AppState,
    input: &CreateInvitationInput,
    request_id: Option<String>,
) -> crate::error::Result<Option<u64>> {
    // Row insert in `Sending` state. Idempotent under retry: if the row
    // already exists with `id = input.invitation_id`, storage returns
    // `Conflict::DuplicateId` and we proceed (Restate retried after the
    // GitHub call succeeded but before the row update).
    let row = DomainGithubInvitation {
        id: input.invitation_id,
        invitation_request_id: input.invitation_request_id,
        repo_id: input.repo_id,
        github_invitation_id: None,
        state: InvitationState::Sending,
        error_message: None,
        created_at: input.now,
        updated_at: input.now,
    };
    match state.storage.insert_github_invitation(&row).await {
        Ok(()) => (),
        Err(ghinvite_core::storage::Error::Conflict(
            ghinvite_core::storage::ConflictKind::DuplicateId,
        )) => {
            // Re-entry; row already in some state. Read it; if terminal, no-op.
            let existing = state
                .storage
                .get_github_invitation(input.invitation_id)
                .await?
                .ok_or(crate::error::HandlerError::Storage(
                    ghinvite_core::storage::Error::NotFound,
                ))?;
            if existing.state.is_terminal() {
                return Ok(None);
            }
            // Fall through and re-attempt the GitHub call.
        }
        Err(e) => return Err(e.into()),
    }

    let repository = repository_identity(&input.repo_full_name)?;

    let outcome = state
        .github
        .add_collaborator(
            input.installation_id,
            repository.owner(),
            repository.name(),
            &input.recipient_login,
            input.permission,
        )
        .await;

    let account =
        crate::invitation_context::load_installation_account(state, input.installation_id).await?;
    let account_id = account.account_id;

    match outcome {
        Ok(Some(github_id)) => {
            // 201 - invitation pending.
            mark_invitation_sent_transition(state, input, account_id, github_id, request_id)
                .await?;
        }
        Ok(None) => {
            // 204 - already a collaborator.
            mark_invitation_already_accepted_transition(state, input, account_id, request_id)
                .await?;
        }
        Err(ghinvite_github::Error::RateLimited { rate_limit, .. }) => {
            // Throttled: no invitation was created and none was refused, so the
            // row stays in `Sending` with nothing audited. The caller defers the
            // next attempt by the wait GitHub's guidance bounds.
            return Ok(Some(
                crate::throttle::backoff(rate_limit.retry_after).as_secs(),
            ));
        }
        Err(e) => {
            let h: crate::error::HandlerError = e.into();
            if !h.is_terminal() {
                // Transient - let Restate retry.
                return Err(h);
            }
            // Terminal 4xx - mark failed, audit, return Ok so Restate does not retry.
            mark_invitation_send_failed_transition(
                state,
                input,
                account_id,
                h.to_string(),
                request_id,
            )
            .await?;
        }
    }

    Ok(None)
}

async fn mark_invitation_sent_transition(
    state: &AppState,
    input: &CreateInvitationInput,
    account_id: u64,
    github_invitation_id: u64,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    state
        .storage
        .update_github_invitation(&ghinvite_core::storage::GithubInvitationUpdate {
            id: input.invitation_id,
            state: InvitationState::Sent,
            github_invitation_id: Some(github_invitation_id),
            error_message: None,
            updated_at: input.now,
        })
        .await?;

    crate::audit::emit(
        state,
        account_id,
        EventType::InvitationSent,
        Actor::System,
        Target::github_invitation(input.invitation_id),
        serde_json::json!({
            "github_invitation_id": github_invitation_id,
            "repo_full_name": input.repo_full_name,
            "recipient": input.recipient_login,
        }),
        request_id,
    )
    .await
}

async fn mark_invitation_already_accepted_transition(
    state: &AppState,
    input: &CreateInvitationInput,
    account_id: u64,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    state
        .storage
        .update_github_invitation(&ghinvite_core::storage::GithubInvitationUpdate {
            id: input.invitation_id,
            state: InvitationState::Accepted,
            github_invitation_id: None,
            error_message: None,
            updated_at: input.now,
        })
        .await?;

    crate::audit::emit(
        state,
        account_id,
        EventType::InvitationAccepted,
        Actor::Github,
        Target::github_invitation(input.invitation_id),
        serde_json::json!({
            "reason": "already_collaborator",
            "repo_full_name": input.repo_full_name,
            "recipient": input.recipient_login,
        }),
        request_id,
    )
    .await
}

async fn mark_invitation_send_failed_transition(
    state: &AppState,
    input: &CreateInvitationInput,
    account_id: u64,
    error_message: String,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    state
        .storage
        .update_github_invitation(&ghinvite_core::storage::GithubInvitationUpdate {
            id: input.invitation_id,
            state: InvitationState::Failed,
            github_invitation_id: None,
            error_message: Some(error_message.clone()),
            updated_at: input.now,
        })
        .await?;

    crate::audit::emit(
        state,
        account_id,
        EventType::InvitationSendFailed,
        Actor::System,
        Target::github_invitation(input.invitation_id),
        serde_json::json!({
            "error": error_message,
            "repo_full_name": input.repo_full_name,
            "recipient": input.recipient_login,
        }),
        request_id,
    )
    .await
}

/// Pure logic: transition the github_invitation row based on a webhook
/// signal. Idempotent: if the row is already in a terminal state, no-op.
pub async fn on_webhook_logic(
    state: &AppState,
    input: &OnWebhookInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    let row = state
        .storage
        .get_github_invitation(input.invitation_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(
            ghinvite_core::storage::Error::NotFound,
        ))?;

    if row.state.is_terminal() {
        return Ok(()); // already settled; webhook is just confirming.
    }

    let context = crate::invitation_context::load_github_invitation_account_context(
        state,
        input.invitation_id,
    )
    .await?;
    debug_assert_eq!(context.invitation.id, input.invitation_id);
    debug_assert_eq!(context.request.id, row.invitation_request_id);
    debug_assert_eq!(context.link.account_id, context.account.account_id);
    debug_assert_eq!(context.requester.user_id, context.request.requester_id);

    match input.action {
        WebhookAction::Accepted => {
            accept_invitation_from_webhook_transition(
                state,
                input.invitation_id,
                context.account.account_id,
                input.at,
                request_id,
            )
            .await
        }
        WebhookAction::Declined => {
            decline_invitation_from_webhook_transition(
                state,
                input.invitation_id,
                context.account.account_id,
                input.at,
                request_id,
            )
            .await
        }
    }
}

async fn accept_invitation_from_webhook_transition(
    state: &AppState,
    invitation_id: GithubInvitationId,
    account_id: u64,
    at: DateTime<Utc>,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    state
        .storage
        .update_github_invitation(&ghinvite_core::storage::GithubInvitationUpdate {
            id: invitation_id,
            state: InvitationState::Accepted,
            github_invitation_id: None,
            error_message: None,
            updated_at: at,
        })
        .await?;

    crate::audit::emit(
        state,
        account_id,
        EventType::InvitationAccepted,
        Actor::Github,
        Target::github_invitation(invitation_id),
        serde_json::json!({"action": "accepted"}),
        request_id,
    )
    .await
}

async fn decline_invitation_from_webhook_transition(
    state: &AppState,
    invitation_id: GithubInvitationId,
    account_id: u64,
    at: DateTime<Utc>,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    state
        .storage
        .update_github_invitation(&ghinvite_core::storage::GithubInvitationUpdate {
            id: invitation_id,
            state: InvitationState::Declined,
            github_invitation_id: None,
            error_message: None,
            updated_at: at,
        })
        .await?;

    crate::audit::emit(
        state,
        account_id,
        EventType::InvitationDeclined,
        Actor::Github,
        Target::github_invitation(invitation_id),
        serde_json::json!({"action": "declined"}),
        request_id,
    )
    .await
}

/// Pure logic: cancel a pending GitHub invitation. Calls
/// `DELETE /repos/.../invitations/{github_id}`; marks row cancelled; emits
/// `invitation.cancelled`. Idempotent: if the row is already terminal
/// or the GitHub invitation is gone (404), proceeds to mark cancelled
/// without re-deleting.
pub async fn cancel_logic(
    state: &AppState,
    input: &CancelInvitationInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    let row = state
        .storage
        .get_github_invitation(input.invitation_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(
            ghinvite_core::storage::Error::NotFound,
        ))?;

    if row.state.is_terminal() {
        return Ok(());
    }

    let context = crate::invitation_context::load_github_invitation_context(
        state,
        input.invitation_id,
        input.installation_id,
    )
    .await?;
    debug_assert_eq!(context.request.id, row.invitation_request_id);
    debug_assert_eq!(context.repo.repo_id, row.repo_id);

    // Call GitHub if we know the upstream id; otherwise skip (row was Sending
    // and never got a 201, so nothing to delete).
    if let Some(github_id) = row.github_invitation_id {
        match state
            .github
            .delete_invitation(
                input.installation_id,
                context.repository.owner(),
                context.repository.name(),
                github_id,
            )
            .await
        {
            Ok(()) => (),
            Err(ghinvite_github::Error::Status { status: 404, .. }) => {
                // Already cancelled / accepted / declined upstream; proceed.
            }
            Err(e) => {
                let h: crate::error::HandlerError = e.into();
                if !h.is_terminal() {
                    return Err(h);
                }
                // Other 4xx — proceed to mark cancelled, audit reason.
            }
        }
    }

    cancel_invitation_transition(
        state,
        input.invitation_id,
        context.account.account_id,
        input.by_user,
        input.at,
        request_id,
    )
    .await
}

async fn cancel_invitation_transition(
    state: &AppState,
    invitation_id: GithubInvitationId,
    account_id: u64,
    by_user: Option<u64>,
    at: DateTime<Utc>,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    state
        .storage
        .update_github_invitation(&ghinvite_core::storage::GithubInvitationUpdate {
            id: invitation_id,
            state: InvitationState::Cancelled,
            github_invitation_id: None,
            error_message: None,
            updated_at: at,
        })
        .await?;

    let actor = match by_user {
        Some(uid) => Actor::User(uid),
        None => Actor::System,
    };

    crate::audit::emit(
        state,
        account_id,
        EventType::InvitationCancelled,
        actor,
        Target::github_invitation(invitation_id),
        serde_json::json!({"by_user": by_user}),
        request_id,
    )
    .await
}

async fn expire_invitation_transition(
    state: &AppState,
    invitation_id: GithubInvitationId,
    account_id: u64,
    at: DateTime<Utc>,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    state
        .storage
        .update_github_invitation(&ghinvite_core::storage::GithubInvitationUpdate {
            id: invitation_id,
            state: InvitationState::Expired,
            github_invitation_id: None,
            error_message: None,
            updated_at: at,
        })
        .await?;

    crate::audit::emit(
        state,
        account_id,
        EventType::InvitationExpired,
        Actor::System,
        Target::github_invitation(invitation_id),
        serde_json::json!({"reason": "tick_expire_no_longer_pending"}),
        request_id,
    )
    .await
}

/// Pure logic: at expiration time, confirm via GitHub list_invitations that
/// the row is still pending; if so, mark expired + audit.
pub async fn tick_expire_logic(
    state: &AppState,
    input: &TickExpireInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    let row = state
        .storage
        .get_github_invitation(input.invitation_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(
            ghinvite_core::storage::Error::NotFound,
        ))?;

    if row.state.is_terminal() {
        return Ok(());
    }

    let context = crate::invitation_context::load_github_invitation_context(
        state,
        input.invitation_id,
        input.installation_id,
    )
    .await?;
    debug_assert_eq!(context.request.id, row.invitation_request_id);
    debug_assert_eq!(context.repo.repo_id, row.repo_id);

    let pending = state
        .github
        .list_invitations(
            input.installation_id,
            context.repository.owner(),
            context.repository.name(),
        )
        .await?;
    let still_pending = row
        .github_invitation_id
        .map(|id| pending.iter().any(|p| p.id == id))
        .unwrap_or(false);

    if !still_pending {
        // Either accepted/declined upstream (webhook missed) or cancelled.
        // Don't fight: leave to webhook reconciliation. Plan 6 / Reconcile.
        return Ok(());
    }

    expire_invitation_transition(
        state,
        input.invitation_id,
        context.account.account_id,
        input.at,
        request_id,
    )
    .await
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::HandlerError;
    use crate::state::AppState;
    use crate::test_support::{
        dt, fixture_github_client, fixture_state_with_storage, fixture_storage,
    };
    use ghinvite_core::audit::{ActorKind, EventType, TargetKind};
    use ghinvite_core::{AccountType, InvitationLinkId, Permission, SelectedRepos, Slug};
    use ghinvite_github::mocks::{Expectation, MockTransport};
    use ghinvite_github::transport::{Method, Response};
    use rand::SeedableRng;
    use std::collections::BTreeMap;
    use std::sync::Arc;

    fn token_mint(installation_id: u64) -> Expectation {
        Expectation {
            method: Method::Post,
            url: format!(
                "https://api.github.test/app/installations/{}/access_tokens",
                installation_id
            ),
            required_headers: BTreeMap::new(),
            expected_body: None,
            response: Response {
                status: 201,
                headers: BTreeMap::new(),
                body: br#"{"token":"ghs_xxx","expires_at":"2099-01-01T00:00:00Z"}"#.to_vec(),
            },
        }
    }

    /// Seed installation, user, invitation_link, request — all FK chain prerequisites.
    async fn seed_chain(state: &AppState) -> RequestId {
        state
            .storage
            .insert_installation(&ghinvite_core::Account {
                installation_id: 9,
                account_id: 100,
                account_login: "acme".into(),
                account_type: AccountType::Organization,
                installed_at: dt("2026-05-04T12:00:00Z"),
                uninstalled_at: None,
                selected_repos: SelectedRepos::All,
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&ghinvite_core::User {
                user_id: 7,
                login: "creator".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&ghinvite_core::User {
                user_id: 8,
                login: "alice".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        let mut rng = rand_chacha::ChaCha8Rng::seed_from_u64(42);
        let link = ghinvite_core::InvitationLink {
            id: InvitationLinkId::new(),
            slug: Slug::generate(&mut rng),
            installation_id: 9,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at: None,
            max_uses: None,
            uses_count: 0,
            permission: Permission::Push,
            approval_required: false,
            description: "AI coding workshop".into(),
            internal_note: None,
            revoked_at: None,
            revoked_by: None,
            repos: vec![],
        };
        state.storage.insert_invitation_link(&link).await.unwrap();
        let req_id = RequestId::new();
        let req = ghinvite_core::InvitationRequest {
            id: req_id,
            invitation_link_id: link.id,
            requester_id: 8,
            justification: None,
            state: ghinvite_core::RequestState::Approved,
            decided_by: Some(7),
            decided_at: Some(dt("2026-05-04T13:00:00Z")),
            decline_reason: None,
            decision_deadline: None,
            created_at: dt("2026-05-04T12:30:00Z"),
        };
        state
            .storage
            .insert_invitation_request_and_increment_uses(&req)
            .await
            .unwrap();
        req_id
    }

    fn sample_input(
        invitation_id: GithubInvitationId,
        request_id: RequestId,
    ) -> CreateInvitationInput {
        CreateInvitationInput {
            invitation_id,
            invitation_request_id: request_id,
            installation_id: 9,
            repo_id: 10,
            repo_full_name: "acme/api".into(),
            recipient_login: "alice".into(),
            permission: Permission::Push,
            now: dt("2026-05-04T13:01:00Z"),
        }
    }

    async fn audit_events(
        storage: &ghinvite_storage_sqlx::SqlxStorage,
        account_id: u64,
    ) -> Vec<ghinvite_core::audit::AuditEvent> {
        storage.debug_list_audit(account_id).await.unwrap()
    }

    async fn state_with_storage_and_mock(
        mock: MockTransport,
    ) -> (AppState, Arc<ghinvite_storage_sqlx::SqlxStorage>) {
        let storage = Arc::new(
            ghinvite_storage_sqlx::SqlxStorage::in_memory()
                .await
                .unwrap(),
        );
        let storage_for_state: Arc<dyn ghinvite_core::storage::Storage> = storage.clone();
        let github = fixture_github_client(Arc::new(mock));
        (AppState::new(storage_for_state, github), storage)
    }

    async fn seed_sending_invitation(state: &AppState, input: &CreateInvitationInput) {
        state
            .storage
            .insert_github_invitation(&DomainGithubInvitation {
                id: input.invitation_id,
                invitation_request_id: input.invitation_request_id,
                repo_id: input.repo_id,
                github_invitation_id: None,
                state: InvitationState::Sending,
                error_message: None,
                created_at: input.now,
                updated_at: input.now,
            })
            .await
            .unwrap();
    }

    #[tokio::test]
    async fn create_201_marks_sent_and_audits() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation {
                method: Method::Put,
                url: "https://api.github.test/repos/acme/api/collaborators/alice".into(),
                required_headers: BTreeMap::new(),
                expected_body: None,
                response: Response {
                    status: 201,
                    headers: BTreeMap::new(),
                    body: br#"{"id": 9988, "invitee":{"id":42,"login":"alice"}}"#.to_vec(),
                },
            },
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;

        let inv_id = GithubInvitationId::new();
        create_logic(&state, &sample_input(inv_id, req_id), None)
            .await
            .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Sent);
        assert_eq!(row.github_invitation_id, Some(9988));
    }

    #[tokio::test]
    async fn create_204_marks_accepted() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation {
                method: Method::Put,
                url: "https://api.github.test/repos/acme/api/collaborators/alice".into(),
                required_headers: BTreeMap::new(),
                expected_body: None,
                response: Response {
                    status: 204,
                    headers: BTreeMap::new(),
                    body: vec![],
                },
            },
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;

        let inv_id = GithubInvitationId::new();
        create_logic(&state, &sample_input(inv_id, req_id), None)
            .await
            .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Accepted);
    }

    #[tokio::test]
    async fn create_422_marks_failed_and_returns_ok() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation::status(
                Method::Put,
                "https://api.github.test/repos/acme/api/collaborators/alice",
                422,
            ),
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;

        let inv_id = GithubInvitationId::new();
        // Terminal 4xx — handler should mark failed and return Ok so Restate
        // does not retry.
        create_logic(&state, &sample_input(inv_id, req_id), None)
            .await
            .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Failed);
        assert!(row.error_message.is_some());
    }

    /// A 403 or 429 answering the collaborator PUT, carrying `headers` and the
    /// `{"message": ...}` body GitHub sends with every refusal.
    fn refused_put(status: u16, headers: &[(&str, &str)], message: &str) -> Vec<Expectation> {
        vec![
            token_mint(9),
            Expectation {
                method: Method::Put,
                url: "https://api.github.test/repos/acme/api/collaborators/alice".into(),
                required_headers: BTreeMap::new(),
                expected_body: None,
                response: Response {
                    status,
                    headers: headers
                        .iter()
                        .map(|(k, v)| ((*k).to_owned(), (*v).to_owned()))
                        .collect(),
                    body: serde_json::json!({ "message": message }).to_string().into(),
                },
            },
        ]
    }

    #[tokio::test]
    async fn create_defers_a_throttled_send_instead_of_failing_it() {
        for (status, headers, message, expected_wait) in [
            (
                403,
                vec![("retry-after", "45")],
                "You have exceeded a secondary rate limit",
                45,
            ),
            // No guidance at all: the documented minute stands in for it.
            (429, vec![], "Too Many Requests", 60),
        ] {
            let mock = MockTransport::scripted(refused_put(status, &headers, message));
            let (state, storage) = state_with_storage_and_mock(mock).await;
            let req_id = seed_chain(&state).await;

            let inv_id = GithubInvitationId::new();
            let deferred = create_logic(&state, &sample_input(inv_id, req_id), None)
                .await
                .unwrap();

            assert_eq!(deferred, Some(expected_wait), "for {status} {message:?}");
            // The invitation is neither sent nor failed: GitHub never decided it.
            let row = state
                .storage
                .get_github_invitation(inv_id)
                .await
                .unwrap()
                .unwrap();
            assert_eq!(row.state, InvitationState::Sending);
            assert_eq!(row.error_message, None);
            assert!(audit_events(&storage, 100).await.is_empty());
        }
    }

    #[tokio::test]
    async fn create_marks_a_permission_denied_403_failed() {
        let mock = MockTransport::scripted(refused_put(
            403,
            &[("x-ratelimit-remaining", "4998")],
            "Resource not accessible by integration",
        ));
        let (state, _storage) = state_with_storage_and_mock(mock).await;
        let req_id = seed_chain(&state).await;

        let inv_id = GithubInvitationId::new();
        // A refusal with no rate-limit evidence is GitHub's answer, so it
        // settles the invitation rather than scheduling another attempt.
        assert_eq!(
            create_logic(&state, &sample_input(inv_id, req_id), None)
                .await
                .unwrap(),
            None
        );

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Failed);
        assert!(row.error_message.is_some());
    }

    #[tokio::test]
    async fn create_502_propagates_transient_for_retry() {
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation::status(
                Method::Put,
                "https://api.github.test/repos/acme/api/collaborators/alice",
                502,
            ),
        ]);
        let (state, storage) = state_with_storage_and_mock(mock).await;
        let req_id = seed_chain(&state).await;

        let inv_id = GithubInvitationId::new();
        let err = create_logic(&state, &sample_input(inv_id, req_id), None)
            .await
            .unwrap_err();
        assert!(!err.is_terminal(), "5xx should be transient: {err:?}");

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Sending);

        let audits = audit_events(&storage, 100).await;
        assert!(audits.is_empty());
    }

    #[tokio::test]
    async fn sent_transition_updates_row_and_audits() {
        let (state, storage) = fixture_state_with_storage().await;
        let req_id = seed_chain(&state).await;
        let inv_id = GithubInvitationId::new();
        let input = sample_input(inv_id, req_id);
        seed_sending_invitation(&state, &input).await;

        mark_invitation_sent_transition(&state, &input, 100, 9988, Some("req-sent".into()))
            .await
            .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Sent);
        assert_eq!(row.github_invitation_id, Some(9988));
        assert_eq!(row.error_message, None);

        let audits = audit_events(&storage, 100).await;
        assert_eq!(audits.len(), 1);
        let event = &audits[0];
        assert_eq!(event.event_type, EventType::InvitationSent);
        assert_eq!(event.actor_kind, ActorKind::System);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::GithubInvitation);
        assert_eq!(event.target_id, inv_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-sent"));
        assert_eq!(
            event.metadata.get("github_invitation_id"),
            Some(&serde_json::json!(9988))
        );
        assert_eq!(
            event.metadata.get("repo_full_name"),
            Some(&serde_json::json!("acme/api"))
        );
        assert_eq!(
            event.metadata.get("recipient"),
            Some(&serde_json::json!("alice"))
        );
    }

    #[tokio::test]
    async fn already_accepted_transition_updates_row_and_audits() {
        let (state, storage) = fixture_state_with_storage().await;
        let req_id = seed_chain(&state).await;
        let inv_id = GithubInvitationId::new();
        let input = sample_input(inv_id, req_id);
        seed_sending_invitation(&state, &input).await;

        mark_invitation_already_accepted_transition(
            &state,
            &input,
            100,
            Some("req-already".into()),
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Accepted);
        assert_eq!(row.github_invitation_id, None);
        assert_eq!(row.error_message, None);

        let audits = audit_events(&storage, 100).await;
        assert_eq!(audits.len(), 1);
        let event = &audits[0];
        assert_eq!(event.event_type, EventType::InvitationAccepted);
        assert_eq!(event.actor_kind, ActorKind::Github);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::GithubInvitation);
        assert_eq!(event.target_id, inv_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-already"));
        assert_eq!(
            event.metadata.get("reason"),
            Some(&serde_json::json!("already_collaborator"))
        );
        assert_eq!(
            event.metadata.get("repo_full_name"),
            Some(&serde_json::json!("acme/api"))
        );
        assert_eq!(
            event.metadata.get("recipient"),
            Some(&serde_json::json!("alice"))
        );
    }

    #[tokio::test]
    async fn send_failed_transition_updates_row_and_audits() {
        let (state, storage) = fixture_state_with_storage().await;
        let req_id = seed_chain(&state).await;
        let inv_id = GithubInvitationId::new();
        let input = sample_input(inv_id, req_id);
        seed_sending_invitation(&state, &input).await;

        mark_invitation_send_failed_transition(
            &state,
            &input,
            100,
            "terminal failure".into(),
            Some("req-failed".into()),
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Failed);
        assert_eq!(row.github_invitation_id, None);
        assert_eq!(row.error_message.as_deref(), Some("terminal failure"));

        let audits = audit_events(&storage, 100).await;
        assert_eq!(audits.len(), 1);
        let event = &audits[0];
        assert_eq!(event.event_type, EventType::InvitationSendFailed);
        assert_eq!(event.actor_kind, ActorKind::System);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::GithubInvitation);
        assert_eq!(event.target_id, inv_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-failed"));
        assert_eq!(
            event.metadata.get("error"),
            Some(&serde_json::json!("terminal failure"))
        );
        assert_eq!(
            event.metadata.get("repo_full_name"),
            Some(&serde_json::json!("acme/api"))
        );
        assert_eq!(
            event.metadata.get("recipient"),
            Some(&serde_json::json!("alice"))
        );
    }

    #[tokio::test]
    async fn create_with_bad_repo_full_name_is_invariant() {
        for bad_full_name in ["no-slash", "/api", "acme/", "acme/team/api"] {
            let storage = fixture_storage().await;
            let mock = MockTransport::scripted(vec![]);
            let github = fixture_github_client(Arc::new(mock));
            let state = AppState::new(storage, github);
            let req_id = seed_chain(&state).await;

            let inv_id = GithubInvitationId::new();
            let mut input = sample_input(inv_id, req_id);
            input.repo_full_name = bad_full_name.into();
            let err = create_logic(&state, &input, None).await.unwrap_err();

            assert!(
                matches!(err, HandlerError::Invariant(_)),
                "{bad_full_name:?} should be an invariant error, got {err:?}"
            );
        }
    }

    /// Helper: from a fresh state, get to "row in Sent state". Returns the
    /// invitation_id that subsequent webhook tests can reference.
    async fn seed_to_sent(state: &AppState, req_id: RequestId) -> GithubInvitationId {
        let inv_id = GithubInvitationId::new();
        let row = DomainGithubInvitation {
            id: inv_id,
            invitation_request_id: req_id,
            repo_id: 10,
            github_invitation_id: Some(9988),
            state: InvitationState::Sent,
            error_message: None,
            created_at: dt("2026-05-04T13:00:00Z"),
            updated_at: dt("2026-05-04T13:00:00Z"),
        };
        state.storage.insert_github_invitation(&row).await.unwrap();
        inv_id
    }

    #[tokio::test]
    async fn webhook_accepted_transitions_and_audits() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![]); // no GitHub calls in this path
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;
        let inv_id = seed_to_sent(&state, req_id).await;

        on_webhook_logic(
            &state,
            &OnWebhookInput {
                invitation_id: inv_id,
                action: WebhookAction::Accepted,
                at: dt("2026-05-04T14:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Accepted);
    }

    #[tokio::test]
    async fn webhook_declined_transitions_and_audits() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let req_id = seed_chain(&state).await;
        let inv_id = seed_to_sent(&state, req_id).await;

        on_webhook_logic(
            &state,
            &OnWebhookInput {
                invitation_id: inv_id,
                action: WebhookAction::Declined,
                at: dt("2026-05-04T14:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Declined);
    }

    #[tokio::test]
    async fn webhook_on_terminal_row_is_idempotent() {
        let (state, storage) = fixture_state_with_storage().await;
        let req_id = seed_chain(&state).await;
        let inv_id = seed_to_sent(&state, req_id).await;

        on_webhook_logic(
            &state,
            &OnWebhookInput {
                invitation_id: inv_id,
                action: WebhookAction::Accepted,
                at: dt("2026-05-04T14:00:00Z"),
            },
            Some("req-first-webhook".into()),
        )
        .await
        .unwrap();

        on_webhook_logic(
            &state,
            &OnWebhookInput {
                invitation_id: inv_id,
                action: WebhookAction::Declined,
                at: dt("2026-05-04T15:00:00Z"),
            },
            Some("req-second-webhook".into()),
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(
            row.state,
            InvitationState::Accepted,
            "terminal state preserved"
        );

        let audits = audit_events(&storage, 100).await;
        let invitation_events: Vec<_> = audits
            .iter()
            .filter(|event| event.target_id == inv_id.to_string())
            .collect();
        assert_eq!(invitation_events.len(), 1);
        assert_eq!(
            invitation_events[0].event_type,
            EventType::InvitationAccepted
        );
        assert_eq!(
            invitation_events[0].request_id.as_deref(),
            Some("req-first-webhook")
        );
    }

    #[tokio::test]
    async fn webhook_unknown_invitation_is_terminal() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);

        let err = on_webhook_logic(
            &state,
            &OnWebhookInput {
                invitation_id: GithubInvitationId::new(),
                action: WebhookAction::Accepted,
                at: dt("2026-05-04T14:00:00Z"),
            },
            None,
        )
        .await
        .unwrap_err();
        assert!(err.is_terminal());
    }

    #[tokio::test]
    async fn webhook_accept_transition_updates_row_and_audits() {
        let (state, storage) = fixture_state_with_storage().await;
        let req_id = seed_chain(&state).await;
        let inv_id = seed_to_sent(&state, req_id).await;

        accept_invitation_from_webhook_transition(
            &state,
            inv_id,
            100,
            dt("2026-05-04T14:00:00Z"),
            Some("req-webhook-accepted".into()),
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Accepted);
        assert_eq!(row.github_invitation_id, None);
        assert_eq!(row.error_message, None);

        let audits = audit_events(&storage, 100).await;
        assert_eq!(audits.len(), 1);
        let event = &audits[0];
        assert_eq!(event.event_type, EventType::InvitationAccepted);
        assert_eq!(event.actor_kind, ActorKind::Github);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::GithubInvitation);
        assert_eq!(event.target_id, inv_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-webhook-accepted"));
        assert_eq!(
            event.metadata.get("action"),
            Some(&serde_json::json!("accepted"))
        );
    }

    #[tokio::test]
    async fn webhook_decline_transition_updates_row_and_audits() {
        let (state, storage) = fixture_state_with_storage().await;
        let req_id = seed_chain(&state).await;
        let inv_id = seed_to_sent(&state, req_id).await;

        decline_invitation_from_webhook_transition(
            &state,
            inv_id,
            100,
            dt("2026-05-04T14:00:00Z"),
            Some("req-webhook-declined".into()),
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Declined);
        assert_eq!(row.github_invitation_id, None);
        assert_eq!(row.error_message, None);

        let audits = audit_events(&storage, 100).await;
        assert_eq!(audits.len(), 1);
        let event = &audits[0];
        assert_eq!(event.event_type, EventType::InvitationDeclined);
        assert_eq!(event.actor_kind, ActorKind::Github);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::GithubInvitation);
        assert_eq!(event.target_id, inv_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-webhook-declined"));
        assert_eq!(
            event.metadata.get("action"),
            Some(&serde_json::json!("declined"))
        );
    }

    #[tokio::test]
    async fn cancel_transition_updates_row_and_audits_user_actor() {
        let (state, storage) = fixture_state_with_storage().await;
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        cancel_invitation_transition(
            &state,
            inv_id,
            100,
            Some(7),
            dt("2026-05-04T15:00:00Z"),
            Some("req-cancel-user".into()),
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Cancelled);
        assert_eq!(row.github_invitation_id, None);
        assert_eq!(row.error_message, None);

        let audits = audit_events(&storage, 100).await;
        assert_eq!(audits.len(), 1);
        let event = &audits[0];
        assert_eq!(event.event_type, EventType::InvitationCancelled);
        assert_eq!(event.actor_kind, ActorKind::User);
        assert_eq!(event.actor_id, Some(7));
        assert_eq!(event.target_kind, TargetKind::GithubInvitation);
        assert_eq!(event.target_id, inv_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-cancel-user"));
        assert_eq!(event.metadata.get("by_user"), Some(&serde_json::json!(7)));
    }

    #[tokio::test]
    async fn cancel_transition_updates_row_and_audits_system_actor() {
        let (state, storage) = fixture_state_with_storage().await;
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        cancel_invitation_transition(
            &state,
            inv_id,
            100,
            None,
            dt("2026-05-04T15:00:00Z"),
            Some("req-cancel-system".into()),
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Cancelled);
        assert_eq!(row.github_invitation_id, None);
        assert_eq!(row.error_message, None);

        let audits = audit_events(&storage, 100).await;
        assert_eq!(audits.len(), 1);
        let event = &audits[0];
        assert_eq!(event.event_type, EventType::InvitationCancelled);
        assert_eq!(event.actor_kind, ActorKind::System);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::GithubInvitation);
        assert_eq!(event.target_id, inv_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-cancel-system"));
        assert_eq!(
            event.metadata.get("by_user"),
            Some(&serde_json::Value::Null)
        );
    }

    #[tokio::test]
    async fn expire_transition_updates_row_and_audits() {
        let (state, storage) = fixture_state_with_storage().await;
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        expire_invitation_transition(
            &state,
            inv_id,
            100,
            dt("2026-05-11T13:00:00Z"),
            Some("req-expire".into()),
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Expired);
        assert_eq!(row.github_invitation_id, None);
        assert_eq!(row.error_message, None);

        let audits = audit_events(&storage, 100).await;
        assert_eq!(audits.len(), 1);
        let event = &audits[0];
        assert_eq!(event.event_type, EventType::InvitationExpired);
        assert_eq!(event.actor_kind, ActorKind::System);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::GithubInvitation);
        assert_eq!(event.target_id, inv_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-expire"));
        assert_eq!(
            event.metadata.get("reason"),
            Some(&serde_json::json!("tick_expire_no_longer_pending"))
        );
    }

    /// Like `seed_to_sent` but with link.repos populated so cancel/expire can
    /// resolve the repo full name from the chain.
    async fn seed_chain_with_repos(state: &AppState) -> (RequestId, GithubInvitationId) {
        state
            .storage
            .insert_installation(&ghinvite_core::Account {
                installation_id: 9,
                account_id: 100,
                account_login: "acme".into(),
                account_type: AccountType::Organization,
                installed_at: dt("2026-05-04T12:00:00Z"),
                uninstalled_at: None,
                selected_repos: SelectedRepos::All,
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&ghinvite_core::User {
                user_id: 7,
                login: "creator".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&ghinvite_core::User {
                user_id: 8,
                login: "alice".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        let mut rng = rand_chacha::ChaCha8Rng::seed_from_u64(7);
        let link = ghinvite_core::InvitationLink {
            id: InvitationLinkId::new(),
            slug: Slug::generate(&mut rng),
            installation_id: 9,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at: None,
            max_uses: None,
            uses_count: 0,
            permission: Permission::Push,
            approval_required: false,
            description: "AI coding workshop".into(),
            internal_note: None,
            revoked_at: None,
            revoked_by: None,
            repos: vec![ghinvite_core::InvitationLinkRepo {
                repo_id: 10,
                repo_full_name: "acme/api".into(),
            }],
        };
        state.storage.insert_invitation_link(&link).await.unwrap();
        let req_id = RequestId::new();
        let req = ghinvite_core::InvitationRequest {
            id: req_id,
            invitation_link_id: link.id,
            requester_id: 8,
            justification: None,
            state: ghinvite_core::RequestState::Approved,
            decided_by: Some(7),
            decided_at: Some(dt("2026-05-04T13:00:00Z")),
            decline_reason: None,
            decision_deadline: None,
            created_at: dt("2026-05-04T12:30:00Z"),
        };
        state
            .storage
            .insert_invitation_request_and_increment_uses(&req)
            .await
            .unwrap();
        let inv_id = GithubInvitationId::new();
        state
            .storage
            .insert_github_invitation(&DomainGithubInvitation {
                id: inv_id,
                invitation_request_id: req_id,
                repo_id: 10,
                github_invitation_id: Some(9988),
                state: InvitationState::Sent,
                error_message: None,
                created_at: dt("2026-05-04T13:00:00Z"),
                updated_at: dt("2026-05-04T13:00:00Z"),
            })
            .await
            .unwrap();
        (req_id, inv_id)
    }

    #[tokio::test]
    async fn cancel_calls_delete_and_marks_cancelled() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation {
                method: Method::Delete,
                url: "https://api.github.test/repos/acme/api/invitations/9988".into(),
                required_headers: BTreeMap::new(),
                expected_body: None,
                response: Response {
                    status: 204,
                    headers: BTreeMap::new(),
                    body: vec![],
                },
            },
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        cancel_logic(
            &state,
            &CancelInvitationInput {
                invitation_id: inv_id,
                installation_id: 9,
                by_user: Some(7),
                at: dt("2026-05-04T15:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Cancelled);
    }

    #[tokio::test]
    async fn cancel_404_proceeds_to_mark_cancelled() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation::status(
                Method::Delete,
                "https://api.github.test/repos/acme/api/invitations/9988",
                404,
            ),
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        cancel_logic(
            &state,
            &CancelInvitationInput {
                invitation_id: inv_id,
                installation_id: 9,
                by_user: None,
                at: dt("2026-05-04T15:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Cancelled);
    }

    #[tokio::test]
    async fn tick_expire_marks_expired_when_still_pending() {
        let storage = fixture_storage().await;
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation::ok_json(
                Method::Get,
                "https://api.github.test/repos/acme/api/invitations?per_page=100",
                serde_json::json!([
                    {
                        "id": 9988,
                        "invitee": {"id": 42, "login": "alice"},
                        "permissions": "write",
                        "created_at": "2026-05-04T13:00:00Z"
                    }
                ]),
            ),
        ]);
        let github = fixture_github_client(Arc::new(mock));
        let state = AppState::new(storage, github);
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        tick_expire_logic(
            &state,
            &TickExpireInput {
                invitation_id: inv_id,
                installation_id: 9,
                at: dt("2026-05-11T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.state, InvitationState::Expired);
    }

    #[tokio::test]
    async fn tick_expire_skips_when_no_longer_pending() {
        let mock = MockTransport::scripted(vec![
            token_mint(9),
            Expectation::ok_json(
                Method::Get,
                "https://api.github.test/repos/acme/api/invitations?per_page=100",
                serde_json::json!([]),
            ),
        ]);
        let (state, storage) = state_with_storage_and_mock(mock).await;
        let (_req_id, inv_id) = seed_chain_with_repos(&state).await;

        tick_expire_logic(
            &state,
            &TickExpireInput {
                invitation_id: inv_id,
                installation_id: 9,
                at: dt("2026-05-11T13:00:00Z"),
            },
            Some("req-expire-skip".into()),
        )
        .await
        .unwrap();

        let row = state
            .storage
            .get_github_invitation(inv_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(
            row.state,
            InvitationState::Sent,
            "row left for webhook to settle"
        );

        let audits = audit_events(&storage, 100).await;
        assert!(audits.is_empty());
    }
}
