//! `InvitationLink` Virtual Object: create, update_metadata, revoke, tick_expiration.

use crate::audit::{Actor, Target};
use crate::state::AppState;
use chrono::{DateTime, Utc};
use ghinvite_core::audit::EventType;
// Aliased to avoid colliding with the `InvitationLink` trait generated by
// `#[restate_sdk::object]` below.
use ghinvite_core::InvitationLink as DomainInvitationLink;
use ghinvite_core::{InvitationLinkId, InvitationLinkRepo, Permission, Slug};
use rand::rngs::OsRng;
use restate_sdk::context::{ContextSideEffects, ObjectContext, RunFuture};
use restate_sdk::errors::TerminalError;
use restate_sdk::serde::Json;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct CreateLinkInput {
    pub installation_id: u64,
    pub account_id: u64,
    pub created_by: u64,
    pub created_at: DateTime<Utc>,
    pub expires_at: Option<DateTime<Utc>>,
    pub max_uses: Option<u32>,
    pub permission: Permission,
    pub approval_required: bool,
    pub description: String,
    pub internal_note: Option<String>,
    pub repos: Vec<InvitationLinkRepo>,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct CreateLinkOutput {
    pub link_id: InvitationLinkId,
    pub slug: String,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct RevokeLinkInput {
    pub link_id: InvitationLinkId,
    pub by_user: u64,
    pub when: DateTime<Utc>,
}

/// Account-admin command; metadata is validated and normalized by the server.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct UpdateLinkMetadataInput {
    pub account_id: u64,
    pub link_id: InvitationLinkId,
    pub by_user: u64,
    pub description: String,
    pub internal_note: Option<String>,
}

/// Journaled before writing so audit retries retain field names and event identity.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct PreparedMetadataUpdate {
    input: UpdateLinkMetadataInput,
    changed_fields: Vec<String>,
    audit_id: ghinvite_core::AuditEventId,
    occurred_at: DateTime<Utc>,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct TickExpirationInput {
    pub link_id: InvitationLinkId,
    pub at: DateTime<Utc>,
}

#[restate_sdk::object]
pub trait InvitationLink {
    async fn create(
        input: Json<CreateLinkInput>,
    ) -> std::result::Result<Json<CreateLinkOutput>, TerminalError>;
    async fn revoke(input: Json<RevokeLinkInput>) -> std::result::Result<(), TerminalError>;
    async fn update_metadata(
        input: Json<UpdateLinkMetadataInput>,
    ) -> std::result::Result<(), TerminalError>;
    async fn tick_expiration(
        input: Json<TickExpirationInput>,
    ) -> std::result::Result<(), TerminalError>;
}

pub struct InvitationLinkImpl {
    pub state: AppState,
}

impl InvitationLink for InvitationLinkImpl {
    async fn update_metadata(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<UpdateLinkMetadataInput>,
    ) -> std::result::Result<(), TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        let Json(prepared) = ctx
            .run(|| async {
                prepare_metadata_update(&self.state, ctx.key(), &input)
                    .await
                    .map(Json)
                    .map_err(crate::error::to_sdk_handler_error)
            })
            .name("prepare_metadata_update")
            .await?;
        ctx.run(|| async {
            apply_metadata_update(&self.state, &prepared, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("update_metadata")
        .await
    }

    async fn create(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<CreateLinkInput>,
    ) -> std::result::Result<Json<CreateLinkOutput>, TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        let Json(output) = ctx
            .run(|| async {
                create_logic(&self.state, &input, request_id.clone())
                    .await
                    .map(Json)
                    .map_err(crate::error::to_sdk_handler_error)
            })
            .name("create")
            .await?;
        Ok(Json(output))
    }

    async fn revoke(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<RevokeLinkInput>,
    ) -> std::result::Result<(), TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            revoke_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("revoke")
        .await
    }

    async fn tick_expiration(
        &self,
        ctx: ObjectContext<'_>,
        input: Json<TickExpirationInput>,
    ) -> std::result::Result<(), TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());
        ctx.run(|| async {
            tick_expiration_logic(&self.state, &input, request_id.clone())
                .await
                .map_err(crate::error::to_sdk_handler_error)
        })
        .name("tick_expiration")
        .await
    }
}

/// Verify the account scope and snapshot changed field names before any write.
/// The trusted web caller authorizes `by_user` as a current account admin.
/// The Restate object must be keyed by `account_id.to_string()`.
pub async fn prepare_metadata_update(
    state: &AppState,
    object_key: &str,
    input: &UpdateLinkMetadataInput,
) -> crate::error::Result<PreparedMetadataUpdate> {
    if object_key != input.account_id.to_string() {
        return Err(ghinvite_core::storage::Error::NotFound.into());
    }
    let link = state
        .storage
        .get_invitation_link_by_id(input.link_id)
        .await?
        .filter(|link| link.account_id == input.account_id)
        .ok_or(ghinvite_core::storage::Error::NotFound)?;
    let mut changed_fields = Vec::new();
    if link.description != input.description {
        changed_fields.push("description".into());
    }
    if link.internal_note != input.internal_note {
        changed_fields.push("internal_note".into());
    }
    Ok(PreparedMetadataUpdate {
        input: input.clone(),
        changed_fields,
        audit_id: ghinvite_core::AuditEventId::new(),
        occurred_at: Utc::now(),
    })
}

/// Apply a journaled command and audit it. Retry with the SAME prepared snapshot
/// after transient failure, never recompute changed fields from the updated row.
pub async fn apply_metadata_update(
    state: &AppState,
    prepared: &PreparedMetadataUpdate,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    let input = &prepared.input;
    state
        .storage
        .update_invitation_link_metadata(
            input.account_id,
            input.link_id,
            &input.description,
            input.internal_note.as_deref(),
        )
        .await?;
    if prepared.changed_fields.is_empty() {
        return Ok(());
    }
    state
        .storage
        .audit(&ghinvite_core::audit::AuditEvent {
            id: prepared.audit_id,
            occurred_at: prepared.occurred_at,
            account_id: input.account_id,
            event_type: EventType::InvitationLinkMetadataUpdated,
            actor_kind: ghinvite_core::audit::ActorKind::User,
            actor_id: Some(input.by_user),
            target_kind: ghinvite_core::audit::TargetKind::InvitationLink,
            target_id: input.link_id.to_string(),
            metadata: serde_json::json!({"changed_fields": prepared.changed_fields}),
            request_id,
        })
        .await?;
    Ok(())
}

/// Pure logic: generate a slug, write the link + repos rows, emit audit.
pub async fn create_logic(
    state: &AppState,
    input: &CreateLinkInput,
    request_id: Option<String>,
) -> crate::error::Result<CreateLinkOutput> {
    create_invitation_link_transition(state, input, request_id).await
}

async fn create_invitation_link_transition(
    state: &AppState,
    input: &CreateLinkInput,
    request_id: Option<String>,
) -> crate::error::Result<CreateLinkOutput> {
    let mut rng = OsRng;
    let slug = Slug::generate(&mut rng);
    let link_id = InvitationLinkId::new();

    let link = DomainInvitationLink {
        id: link_id,
        slug: slug.clone(),
        installation_id: input.installation_id,
        account_id: input.account_id,
        created_by: input.created_by,
        created_at: input.created_at,
        expires_at: input.expires_at,
        max_uses: input.max_uses,
        uses_count: 0,
        permission: input.permission,
        approval_required: input.approval_required,
        description: input.description.clone(),
        internal_note: input.internal_note.clone(),
        revoked_at: None,
        revoked_by: None,
        repos: input.repos.clone(),
    };

    state.storage.insert_invitation_link(&link).await?;

    crate::audit::emit(
        state,
        input.account_id,
        EventType::InvitationLinkCreated,
        Actor::User(input.created_by),
        Target::invitation_link(link_id),
        serde_json::json!({
            "permission": input.permission.to_string(),
            "approval_required": input.approval_required,
            "max_uses": input.max_uses,
            "repo_count": input.repos.len(),
        }),
        request_id,
    )
    .await?;

    Ok(CreateLinkOutput {
        link_id,
        slug: slug.as_str().to_string(),
    })
}

/// Pure logic: stamp `revoked_at`/`revoked_by`; emit audit. Idempotent on
/// double-revoke (storage returns NotFound when no-op; we treat as Ok).
pub async fn revoke_logic(
    state: &AppState,
    input: &RevokeLinkInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    revoke_invitation_link_transition(state, input, request_id).await
}

async fn revoke_invitation_link_transition(
    state: &AppState,
    input: &RevokeLinkInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    match state
        .storage
        .mark_invitation_link_revoked(input.link_id, input.by_user, input.when)
        .await
    {
        Ok(()) => (),
        Err(ghinvite_core::storage::Error::NotFound) => return Ok(()),
        Err(e) => return Err(e.into()),
    }

    let link = state
        .storage
        .get_invitation_link_by_id(input.link_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(
            ghinvite_core::storage::Error::NotFound,
        ))?;

    crate::audit::emit(
        state,
        link.account_id,
        EventType::InvitationLinkRevoked,
        Actor::User(input.by_user),
        Target::invitation_link(input.link_id),
        serde_json::json!({"by_user": input.by_user}),
        request_id,
    )
    .await
}

/// Pure logic: if the link is past its expiry and not already revoked, emit
/// `invitation_link.expired`. No state mutation — `is_active(now)` already reflects
/// the expiry. Idempotent under repeated calls.
pub async fn tick_expiration_logic(
    state: &AppState,
    input: &TickExpirationInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    expire_invitation_link_transition(state, input, request_id).await
}

async fn expire_invitation_link_transition(
    state: &AppState,
    input: &TickExpirationInput,
    request_id: Option<String>,
) -> crate::error::Result<()> {
    let link = state
        .storage
        .get_invitation_link_by_id(input.link_id)
        .await?
        .ok_or(crate::error::HandlerError::Storage(
            ghinvite_core::storage::Error::NotFound,
        ))?;

    if link.revoked_at.is_some() {
        return Ok(());
    }
    let Some(expires) = link.expires_at else {
        return Err(crate::error::HandlerError::Invariant(format!(
            "tick_expiration fired for link {} which has no expires_at",
            input.link_id
        )));
    };
    if input.at < expires {
        return Ok(());
    }

    crate::audit::emit(
        state,
        link.account_id,
        EventType::InvitationLinkExpired,
        Actor::System,
        Target::invitation_link(input.link_id),
        serde_json::json!({"expired_at": input.at.to_rfc3339()}),
        request_id,
    )
    .await
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::HandlerError;
    use crate::test_support::{dt, fixture_state, fixture_state_with_storage};
    use ghinvite_core::audit::{ActorKind, EventType, TargetKind};
    use ghinvite_core::{AccountType, SelectedRepos};

    async fn seed_installation_and_user(state: &AppState) {
        let acct = ghinvite_core::Account {
            installation_id: 1,
            account_id: 100,
            account_login: "acme".into(),
            account_type: AccountType::Organization,
            installed_at: dt("2026-05-04T12:00:00Z"),
            uninstalled_at: None,
            selected_repos: SelectedRepos::All,
        };
        state.storage.insert_installation(&acct).await.unwrap();
        let user = ghinvite_core::User {
            user_id: 7,
            login: "creator".into(),
            avatar_url: None,
            last_seen_at: dt("2026-05-04T12:00:00Z"),
        };
        state.storage.upsert_user(&user).await.unwrap();
    }

    fn sample_input() -> CreateLinkInput {
        CreateLinkInput {
            installation_id: 1,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at: Some(dt("2026-06-03T12:00:00Z")),
            max_uses: Some(5),
            permission: Permission::Pull,
            approval_required: true,
            description: "AI coding workshop".into(),
            internal_note: Some("test".into()),
            repos: vec![InvitationLinkRepo {
                repo_id: 10,
                repo_full_name: "acme/api".into(),
            }],
        }
    }

    async fn audit_events(
        storage: &ghinvite_storage_sqlx::SqlxStorage,
        account_id: u64,
    ) -> Vec<ghinvite_core::audit::AuditEvent> {
        storage.debug_list_audit(account_id).await.unwrap()
    }

    #[tokio::test]
    async fn metadata_update_changes_only_metadata_and_audits_field_names() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        let mut expected = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        let input = UpdateLinkMetadataInput {
            account_id: 100,
            link_id: out.link_id,
            by_user: 7,
            description: "Corrected private description".into(),
            internal_note: Some("Corrected private\nnote".into()),
        };
        let prepared = prepare_metadata_update(&state, "100", &input)
            .await
            .unwrap();
        apply_metadata_update(&state, &prepared, Some("req-metadata".into()))
            .await
            .unwrap();
        expected.description = input.description;
        expected.internal_note = input.internal_note;
        assert_eq!(
            state
                .storage
                .get_invitation_link_by_id(out.link_id)
                .await
                .unwrap(),
            Some(expected)
        );

        let events = audit_events(&storage, 100).await;
        assert_eq!(events.len(), 2);
        let event = &events[1];
        assert_eq!(event.event_type, EventType::InvitationLinkMetadataUpdated);
        assert_eq!(
            serde_json::to_value(event.event_type).unwrap(),
            "invitation_link.metadata_updated"
        );
        assert_eq!(event.account_id, 100);
        assert_eq!(event.actor_kind, ActorKind::User);
        assert_eq!(event.actor_id, Some(7));
        assert_eq!(event.target_kind, TargetKind::InvitationLink);
        assert_eq!(event.target_id, out.link_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-metadata"));
        assert_eq!(
            event.metadata,
            serde_json::json!({"changed_fields": ["description", "internal_note"]})
        );
    }

    #[tokio::test]
    async fn metadata_update_replay_after_success_keeps_exactly_one_audit_event() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        let input = UpdateLinkMetadataInput {
            account_id: 100,
            link_id: out.link_id,
            by_user: 7,
            description: "Corrected private description".into(),
            internal_note: None,
        };
        let prepared = prepare_metadata_update(&state, "100", &input)
            .await
            .unwrap();
        let journal = serde_json::to_vec(&prepared).unwrap();
        apply_metadata_update(&state, &prepared, Some("req-replay".into()))
            .await
            .unwrap();
        let first_events = audit_events(&storage, 100).await;
        assert_eq!(first_events.len(), 2);

        let replayed = serde_json::from_slice(&journal).unwrap();
        apply_metadata_update(&state, &replayed, Some("req-replay".into()))
            .await
            .unwrap();
        assert_eq!(audit_events(&storage, 100).await, first_events);
    }

    #[tokio::test]
    async fn metadata_update_replays_after_audit_insert_acknowledgement_loss() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        let input = UpdateLinkMetadataInput {
            account_id: 100,
            link_id: out.link_id,
            by_user: 7,
            description: "Corrected private description".into(),
            internal_note: None,
        };
        let prepared = prepare_metadata_update(&state, "100", &input)
            .await
            .unwrap();
        let journal = serde_json::to_vec(&prepared).unwrap();
        storage.debug_set_audit_ack_loss(true).await.unwrap();
        let err = apply_metadata_update(&state, &prepared, Some("req-ack-loss".into()))
            .await
            .unwrap_err();
        assert!(!err.is_terminal());
        let committed_events = audit_events(&storage, 100).await;
        assert_eq!(
            committed_events.len(),
            2,
            "audit insert committed despite error"
        );
        let event = &committed_events[1];
        assert_eq!(event.event_type, EventType::InvitationLinkMetadataUpdated);
        assert_eq!(
            event.metadata,
            serde_json::json!({"changed_fields": ["description", "internal_note"]})
        );

        storage.debug_set_audit_ack_loss(false).await.unwrap();
        let replayed = serde_json::from_slice(&journal).unwrap();
        apply_metadata_update(&state, &replayed, Some("req-ack-loss".into()))
            .await
            .unwrap();
        assert_eq!(audit_events(&storage, 100).await, committed_events);
    }

    #[tokio::test]
    async fn metadata_update_retries_audit_with_journaled_fields_after_write_succeeds() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        let input = UpdateLinkMetadataInput {
            account_id: 100,
            link_id: out.link_id,
            by_user: 7,
            description: sample_input().description,
            internal_note: None,
        };
        let prepared = prepare_metadata_update(&state, "100", &input)
            .await
            .unwrap();
        // Simulate Restate persisting the preparation before the transition runs.
        let journal = serde_json::to_vec(&prepared).unwrap();
        state
            .storage
            .insert_invitation_request_and_increment_uses(&ghinvite_core::InvitationRequest {
                id: ghinvite_core::RequestId::new(),
                invitation_link_id: out.link_id,
                requester_id: 7,
                justification: None,
                state: ghinvite_core::RequestState::Pending,
                decided_by: None,
                decided_at: None,
                decline_reason: None,
                decision_deadline: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            })
            .await
            .unwrap();
        state
            .storage
            .mark_invitation_link_revoked(out.link_id, 7, dt("2026-05-04T13:00:00Z"))
            .await
            .unwrap();
        let mut expected = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        expected.internal_note = None;

        storage.debug_set_audit_failure(true).await.unwrap();
        let err = apply_metadata_update(&state, &prepared, Some("req-retry".into()))
            .await
            .unwrap_err();
        assert!(!err.is_terminal(), "audit failure must be retried");
        assert_eq!(
            state
                .storage
                .get_invitation_link_by_id(out.link_id)
                .await
                .unwrap(),
            Some(expected.clone())
        );
        assert_eq!(audit_events(&storage, 100).await.len(), 1);

        storage.debug_set_audit_failure(false).await.unwrap();
        let replayed: PreparedMetadataUpdate = serde_json::from_slice(&journal).unwrap();
        apply_metadata_update(&state, &replayed, Some("req-retry".into()))
            .await
            .unwrap();
        assert_eq!(
            state
                .storage
                .get_invitation_link_by_id(out.link_id)
                .await
                .unwrap(),
            Some(expected)
        );
        let events = audit_events(&storage, 100).await;
        assert_eq!(events.len(), 2);
        assert_eq!(
            events[1].event_type,
            EventType::InvitationLinkMetadataUpdated
        );
        assert_eq!(
            events[1].metadata,
            serde_json::json!({"changed_fields": ["internal_note"]})
        );
        assert_eq!(events[1].request_id.as_deref(), Some("req-retry"));
    }

    #[tokio::test]
    async fn metadata_update_conceals_missing_foreign_links_and_wrong_object_keys() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        let before = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap();
        for (object_key, account_id, link_id) in [
            ("100", 100, InvitationLinkId::new()),
            ("200", 200, out.link_id),
            ("200", 100, out.link_id),
        ] {
            let input = UpdateLinkMetadataInput {
                account_id,
                link_id,
                by_user: 7,
                description: "Forbidden edit".into(),
                internal_note: None,
            };
            let err = prepare_metadata_update(&state, object_key, &input)
                .await
                .unwrap_err();
            assert!(matches!(
                err,
                HandlerError::Storage(ghinvite_core::storage::Error::NotFound)
            ));
            assert!(err.is_terminal());
            assert_eq!(err.to_string(), "not found");
        }
        assert_eq!(
            state
                .storage
                .get_invitation_link_by_id(out.link_id)
                .await
                .unwrap(),
            before
        );
        assert_eq!(audit_events(&storage, 100).await.len(), 1);
        assert!(audit_events(&storage, 200).await.is_empty());
    }

    #[tokio::test]
    async fn metadata_update_noop_succeeds_without_audit_and_single_field_edits_are_precise() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        let mut input = UpdateLinkMetadataInput {
            account_id: 100,
            link_id: out.link_id,
            by_user: 7,
            description: sample_input().description,
            internal_note: sample_input().internal_note,
        };
        let prepared = prepare_metadata_update(&state, "100", &input)
            .await
            .unwrap();
        apply_metadata_update(&state, &prepared, None)
            .await
            .unwrap();
        assert_eq!(audit_events(&storage, 100).await.len(), 1);

        input.description = "Description only".into();
        let prepared = prepare_metadata_update(&state, "100", &input)
            .await
            .unwrap();
        apply_metadata_update(&state, &prepared, None)
            .await
            .unwrap();
        let events = audit_events(&storage, 100).await;
        assert_eq!(events.len(), 2);
        assert_eq!(
            events[1].metadata,
            serde_json::json!({"changed_fields": ["description"]})
        );

        input.internal_note = None;
        let prepared = prepare_metadata_update(&state, "100", &input)
            .await
            .unwrap();
        apply_metadata_update(&state, &prepared, None)
            .await
            .unwrap();
        input.internal_note = Some("New private\nnote".into());
        let prepared = prepare_metadata_update(&state, "100", &input)
            .await
            .unwrap();
        apply_metadata_update(&state, &prepared, None)
            .await
            .unwrap();
        let events = audit_events(&storage, 100).await;
        assert_eq!(events.len(), 4);
        for event in &events[2..] {
            assert_eq!(
                event.metadata,
                serde_json::json!({"changed_fields": ["internal_note"]})
            );
        }
        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.description, "Description only");
        assert_eq!(link.internal_note.as_deref(), Some("New private\nnote"));
    }

    #[tokio::test]
    async fn metadata_update_accepts_each_inactive_state_without_reactivation() {
        for inactive in ["expired", "exhausted", "revoked"] {
            let (state, storage) = fixture_state_with_storage().await;
            seed_installation_and_user(&state).await;
            let mut creation = sample_input();
            creation.expires_at = if inactive == "expired" {
                Some(dt("2020-01-01T00:00:00Z"))
            } else {
                None
            };
            creation.max_uses = if inactive == "exhausted" {
                Some(0)
            } else {
                None
            };
            let out = create_logic(&state, &creation, None).await.unwrap();
            if inactive == "revoked" {
                state
                    .storage
                    .mark_invitation_link_revoked(out.link_id, 7, dt("2026-05-04T13:00:00Z"))
                    .await
                    .unwrap();
            }
            let mut expected = state
                .storage
                .get_invitation_link_by_id(out.link_id)
                .await
                .unwrap()
                .unwrap();
            assert!(!expected.is_active(Utc::now()), "{inactive}");
            // Guardrail fields submitted by an untrusted form are not command fields.
            let input: UpdateLinkMetadataInput = serde_json::from_value(serde_json::json!({
                "account_id": 100,
                "link_id": out.link_id,
                "by_user": 7,
                "description": "Updated inactive link",
                "internal_note": null,
                "permission": "admin",
                "approval_required": false,
                "max_uses": 999,
                "uses_count": 0,
                "expires_at": null,
                "revoked_at": null,
                "repos": [],
                "slug": "replacement"
            }))
            .unwrap();
            let prepared = prepare_metadata_update(&state, "100", &input)
                .await
                .unwrap();
            apply_metadata_update(&state, &prepared, None)
                .await
                .unwrap();
            expected.description = "Updated inactive link".into();
            expected.internal_note = None;
            let actual = state
                .storage
                .get_invitation_link_by_id(out.link_id)
                .await
                .unwrap()
                .unwrap();
            assert_eq!(actual, expected, "{inactive}");
            assert!(!actual.is_active(Utc::now()), "{inactive}");
            assert_eq!(audit_events(&storage, 100).await.len(), 2);
        }
    }

    #[tokio::test]
    async fn metadata_update_failed_write_does_not_audit() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        let input = UpdateLinkMetadataInput {
            account_id: 100,
            link_id: out.link_id,
            by_user: 7,
            description: "Changed".into(),
            internal_note: None,
        };
        let prepared = prepare_metadata_update(&state, "100", &input)
            .await
            .unwrap();
        let (missing_state, storage) = fixture_state_with_storage().await;
        let err = apply_metadata_update(&missing_state, &prepared, None)
            .await
            .unwrap_err();
        assert!(matches!(
            err,
            HandlerError::Storage(ghinvite_core::storage::Error::NotFound)
        ));
        assert!(audit_events(&storage, 100).await.is_empty());
    }

    #[tokio::test]
    async fn create_inserts_link_with_generated_slug() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;

        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        assert_eq!(out.slug.len(), 16);

        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.slug.as_str(), out.slug);
        assert_eq!(link.repos.len(), 1);
        assert_eq!(link.repos[0].repo_full_name, "acme/api");
        assert_eq!(link.uses_count, 0);
        assert_eq!(link.permission, Permission::Pull);
        assert!(link.approval_required);
        assert_eq!(link.description, "AI coding workshop");
    }

    #[tokio::test]
    async fn create_transition_inserts_link_and_audits() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;

        let out =
            create_invitation_link_transition(&state, &sample_input(), Some("req-create".into()))
                .await
                .unwrap();

        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.slug.as_str(), out.slug);
        assert_eq!(link.repos.len(), 1);

        let audits = audit_events(&storage, 100).await;
        assert_eq!(audits.len(), 1);
        let event = &audits[0];
        assert_eq!(event.event_type, EventType::InvitationLinkCreated);
        assert_eq!(event.actor_kind, ActorKind::User);
        assert_eq!(event.actor_id, Some(7));
        assert_eq!(event.target_kind, TargetKind::InvitationLink);
        assert_eq!(event.target_id, out.link_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-create"));
        assert_eq!(
            event.metadata.get("permission"),
            Some(&serde_json::json!("pull"))
        );
        assert_eq!(
            event.metadata.get("approval_required"),
            Some(&serde_json::json!(true))
        );
        assert_eq!(event.metadata.get("max_uses"), Some(&serde_json::json!(5)));
        assert_eq!(
            event.metadata.get("repo_count"),
            Some(&serde_json::json!(1))
        );
        assert_eq!(link.description, "AI coding workshop");
        assert!(event.metadata.get("description").is_none());
    }

    #[tokio::test]
    async fn create_unknown_installation_is_terminal() {
        let state = fixture_state().await;
        let mut input = sample_input();
        input.installation_id = 999;
        let err = create_logic(&state, &input, None).await.unwrap_err();
        assert!(err.is_terminal());
    }

    #[tokio::test]
    async fn create_no_repos_is_allowed() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;

        let mut input = sample_input();
        input.repos.clear();
        let out = create_logic(&state, &input, None).await.unwrap();
        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert!(link.repos.is_empty());
    }

    #[tokio::test]
    async fn revoke_marks_and_audits() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();

        revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.revoked_by, Some(7));
        assert!(link.revoked_at.is_some());
    }

    #[tokio::test]
    async fn revoke_transition_marks_and_audits_once() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out =
            create_invitation_link_transition(&state, &sample_input(), Some("req-create".into()))
                .await
                .unwrap();

        revoke_invitation_link_transition(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            Some("req-revoke".into()),
        )
        .await
        .unwrap();

        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(link.revoked_by, Some(7));
        assert_eq!(link.revoked_at, Some(dt("2026-05-04T13:00:00Z")));

        revoke_invitation_link_transition(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T14:00:00Z"),
            },
            Some("req-revoke-again".into()),
        )
        .await
        .unwrap();

        let audits = audit_events(&storage, 100).await;
        let revoked: Vec<_> = audits
            .iter()
            .filter(|event| event.event_type == EventType::InvitationLinkRevoked)
            .collect();
        assert_eq!(revoked.len(), 1);
        let event = revoked[0];
        assert_eq!(event.actor_kind, ActorKind::User);
        assert_eq!(event.actor_id, Some(7));
        assert_eq!(event.target_kind, TargetKind::InvitationLink);
        assert_eq!(event.target_id, out.link_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-revoke"));
        assert_eq!(event.metadata.get("by_user"), Some(&serde_json::json!(7)));
    }

    #[tokio::test]
    async fn revoke_already_revoked_is_idempotent() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();

        revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        // Second revoke on already-revoked link.
        let result = revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T14:00:00Z"),
            },
            None,
        )
        .await;
        assert!(
            result.is_ok(),
            "double-revoke should be idempotent: {result:?}"
        );
    }

    #[tokio::test]
    async fn tick_expiration_emits_when_past_expiry() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();

        tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2026-06-03T12:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();
    }

    #[tokio::test]
    async fn expire_transition_emits_audit_without_state_mutation() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out =
            create_invitation_link_transition(&state, &sample_input(), Some("req-create".into()))
                .await
                .unwrap();
        let expired_at = dt("2026-06-03T12:00:00Z");

        expire_invitation_link_transition(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: expired_at,
            },
            Some("req-expire".into()),
        )
        .await
        .unwrap();

        let link = state
            .storage
            .get_invitation_link_by_id(out.link_id)
            .await
            .unwrap()
            .unwrap();
        assert!(link.revoked_at.is_none());
        assert_eq!(link.uses_count, 0);
        assert!(!link.is_active(expired_at));

        let audits = audit_events(&storage, 100).await;
        let event = audits
            .iter()
            .find(|event| event.event_type == EventType::InvitationLinkExpired)
            .expect("expiration should emit audit event");
        assert_eq!(event.actor_kind, ActorKind::System);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::InvitationLink);
        assert_eq!(event.target_id, out.link_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-expire"));
        assert_eq!(
            event.metadata.get("expired_at"),
            Some(&serde_json::json!(expired_at.to_rfc3339()))
        );
    }

    #[tokio::test]
    async fn tick_expiration_skips_revoked_link() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;
        let out = create_logic(&state, &sample_input(), None).await.unwrap();
        revoke_logic(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2026-06-03T12:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();
    }

    #[tokio::test]
    async fn expire_transition_skips_early_and_revoked_links_without_audit() {
        let (state, storage) = fixture_state_with_storage().await;
        seed_installation_and_user(&state).await;
        let out =
            create_invitation_link_transition(&state, &sample_input(), Some("req-create".into()))
                .await
                .unwrap();

        expire_invitation_link_transition(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2026-06-03T11:59:59Z"),
            },
            Some("req-early".into()),
        )
        .await
        .unwrap();

        revoke_invitation_link_transition(
            &state,
            &RevokeLinkInput {
                link_id: out.link_id,
                by_user: 7,
                when: dt("2026-05-04T13:00:00Z"),
            },
            Some("req-revoke".into()),
        )
        .await
        .unwrap();

        expire_invitation_link_transition(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2026-06-03T12:00:00Z"),
            },
            Some("req-expire-revoked".into()),
        )
        .await
        .unwrap();

        let audits = audit_events(&storage, 100).await;
        let expired_count = audits
            .iter()
            .filter(|event| event.event_type == EventType::InvitationLinkExpired)
            .count();
        assert_eq!(expired_count, 0);
    }

    #[tokio::test]
    async fn tick_expiration_unknown_link_is_terminal() {
        let state = fixture_state().await;
        let err = tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: InvitationLinkId::new(),
                at: dt("2026-06-03T12:00:00Z"),
            },
            None,
        )
        .await
        .unwrap_err();
        assert!(err.is_terminal());
    }

    #[tokio::test]
    async fn tick_expiration_no_expires_at_is_terminal_invariant() {
        let state = fixture_state().await;
        seed_installation_and_user(&state).await;

        let mut no_expiry = sample_input();
        no_expiry.expires_at = None;
        let out = create_logic(&state, &no_expiry, None).await.unwrap();

        let err = tick_expiration_logic(
            &state,
            &TickExpirationInput {
                link_id: out.link_id,
                at: dt("2099-01-01T00:00:00Z"),
            },
            None,
        )
        .await
        .unwrap_err();
        assert!(matches!(err, HandlerError::Invariant(_)));
        assert!(err.is_terminal());
    }
}
