//! `InvitationRequest` Workflow: submit the request, race admin decision against
//! timeout, dispatch to GithubInvitation on approval.

use crate::audit::{Actor, Target};
use crate::error::HandlerError;
use crate::state::AppState;
use chrono::{DateTime, Duration, Utc};
use ghinvite_core::audit::EventType;
// Aliased to avoid colliding with the `InvitationRequest` trait generated by
// `#[restate_sdk::workflow]` below. Task 16's pure-logic helpers insert
// `DomainInvitationRequest` rows; the alias lives here so the import set
// matches the established pattern (see `invitation_link.rs` / `github_invitation.rs`).
use ghinvite_core::InvitationRequest as DomainInvitationRequest;
use ghinvite_core::{RequestId, RequestState};
use restate_sdk::context::{
    ContextClient, ContextPromises, ContextSideEffects, ContextTimers, RunFuture,
    SharedWorkflowContext, WorkflowContext,
};
use restate_sdk::errors::TerminalError;
use restate_sdk::serde::Json;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Maximum time we keep a request "pending awaiting admin decision".
/// Per spec §Q8: `min(link.expires_at - now, 7d)`.
pub const MAX_DECISION_WAIT: Duration = Duration::days(7);

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub struct SubmitRequestInput {
    pub request_id: RequestId,
    pub invitation_link_id: ghinvite_core::InvitationLinkId,
    pub requester_id: u64,
    pub justification: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// Decision payload — admin's approve/decline handler in Plan 5
/// resolves the "decision" durable promise with this.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub enum Decision {
    Approve {
        decided_by: u64,
        decided_at: DateTime<Utc>,
    },
    Decline {
        decided_by: u64,
        decided_at: DateTime<Utc>,
        reason: Option<String>,
    },
}

#[restate_sdk::workflow]
pub trait InvitationRequest {
    /// One-shot workflow per `request_id`. Returns the final state.
    async fn submit(
        input: Json<SubmitRequestInput>,
    ) -> std::result::Result<Json<RequestState>, TerminalError>;

    /// Resolve the "decision" durable promise in `submit` with an Approve/Decline decision.
    /// Called by the admin's approve/decline handler (Plan 5).
    #[shared]
    async fn decide(decision: Json<Decision>) -> std::result::Result<(), TerminalError>;
}

pub struct InvitationRequestImpl {
    pub state: AppState,
}

impl InvitationRequest for InvitationRequestImpl {
    async fn submit(
        &self,
        ctx: WorkflowContext<'_>,
        input: Json<SubmitRequestInput>,
    ) -> std::result::Result<Json<RequestState>, TerminalError> {
        let Json(input) = input;
        let request_id = Some(ctx.invocation_id().to_string());

        // Phase 1: insert pending row, emit `request.created`, classify outcome.
        let Json(outcome) = {
            let state = self.state.clone();
            let input = input.clone();
            let request_id = request_id.clone();
            ctx.run(move || {
                let state = state.clone();
                let input = input.clone();
                let request_id = request_id.clone();
                async move {
                    pre_decision_logic(&state, &input, input.created_at, request_id)
                        .await
                        .map(Json)
                        .map_err(crate::error::to_sdk_handler_error)
                }
            })
            .name("pre_decision")
            .await?
        };

        // Phase 2: pick the AppliedDecision that the apply step will record.
        // - AutoApprove: skip the awakeable race; stamp `at = input.created_at`.
        // - PendingDecision: race admin awakeable against the deadline timer.
        let account_id = match &outcome {
            PreDecisionOutcome::AutoApprove { account_id } => *account_id,
            PreDecisionOutcome::PendingDecision { account_id, .. } => *account_id,
        };
        let applied: AppliedDecision = match outcome {
            PreDecisionOutcome::AutoApprove { .. } => AppliedDecision::AutoApprove {
                at: input.created_at,
            },
            PreDecisionOutcome::PendingDecision {
                decision_deadline, ..
            } => {
                // The durable promise name "decision" is deterministically derived
                // from the workflow id, making the resolve target deterministic.
                // Plan 5's admin server function resolves it via Restate's SDK.
                let promise = ctx.promise::<Json<Decision>>("decision");

                // ctx.sleep takes a Duration; our deadline is absolute. The
                // workflow handler runs at `created_at` (or replay time);
                // `created_at` is the most stable reference we have without
                // a fresh `ctx.run(|| now())`.
                let wait = decision_deadline - input.created_at;
                let wait = if wait <= Duration::zero() {
                    std::time::Duration::ZERO
                } else {
                    // chrono::Duration -> std::time::Duration; safe because we
                    // just bounded `wait` to >= 0 and `MAX_DECISION_WAIT` is days.
                    wait.to_std().unwrap_or(std::time::Duration::ZERO)
                };
                let sleep = ctx.sleep(wait);

                // The Restate SDK ships its own `select!` (DurableFuture-aware),
                // semantically the same as tokio's. Either branch yields an
                // `AppliedDecision` with `at = decision_deadline` (timer) or the
                // admin's `decided_at` (awakeable).
                restate_sdk::select! {
                    res = promise => {
                        let Json(decision) = res?;
                        match decision {
                            Decision::Approve { decided_by, decided_at } => AppliedDecision::Approve {
                                decided_by,
                                at: decided_at,
                            },
                            Decision::Decline { decided_by, decided_at, reason } => AppliedDecision::Decline {
                                decided_by,
                                at: decided_at,
                                reason,
                            },
                        }
                    },
                    _ = sleep => AppliedDecision::Expire {
                        at: decision_deadline,
                    },
                }
            }
        };

        // Phase 3: durably record the decision and emit the audit row.
        let Json(final_state) = {
            let state = self.state.clone();
            let request_id_inner = request_id.clone();
            let req_id = input.request_id;
            let decision = applied.clone();
            ctx.run(move || {
                let state = state.clone();
                let request_id_inner = request_id_inner.clone();
                let decision = decision.clone();
                async move {
                    apply_decision_logic(&state, req_id, account_id, decision, request_id_inner)
                        .await
                        .map(Json)
                        .map_err(crate::error::to_sdk_handler_error)
                }
            })
            .name("apply_decision")
            .await?
        };

        // Phase 4: on approval, fan out per-repo to GithubInvitation::create.
        if final_state == RequestState::Approved {
            // Build the per-repo dispatch inputs in a journaled run so each
            // GithubInvitationId is stable across replays.
            let Json(inputs) = {
                let state = self.state.clone();
                let req_id = input.request_id;
                let now = input.created_at;
                ctx.run(move || {
                    let state = state.clone();
                    async move {
                        build_dispatch_inputs(&state, req_id, now)
                            .await
                            .map(Json)
                            .map_err(crate::error::to_sdk_handler_error)
                    }
                })
                .name("build_dispatch_inputs")
                .await?
            };

            for inv_input in inputs {
                ctx.object_client::<crate::github_invitation::GithubInvitationClient>(
                    inv_input.invitation_id.to_string(),
                )
                .create(Json(inv_input))
                .send();
            }
        }

        Ok(Json(final_state))
    }

    async fn decide(
        &self,
        ctx: SharedWorkflowContext<'_>,
        decision: Json<Decision>,
    ) -> std::result::Result<(), TerminalError> {
        // Keep Json<Decision> intact: submit waits on the same wrapped promise type.
        ctx.resolve_promise("decision", decision);
        Ok(())
    }
}

/// Outcome of the pre-decision phase. Drives the workflow handler's branching.
/// Wrapped in `Json<PreDecisionOutcome>` at the `ctx.run("pre_decision")`
/// boundary so Restate journals it with SDK-managed JSON framing.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub enum PreDecisionOutcome {
    /// Link auto-approves; no awakeable race needed. Carries `account_id` so
    /// `apply_decision_logic` can audit without re-reading the link.
    AutoApprove { account_id: u64 },
    /// Pending admin decision; workflow must race awakeable vs. timeout.
    PendingDecision {
        account_id: u64,
        decision_deadline: DateTime<Utc>,
    },
}

/// Concrete decision the workflow has resolved on. Distinct from
/// [`Decision`] (the awakeable payload from admin) because the workflow may
/// also auto-approve or expire on its own.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize)]
pub enum AppliedDecision {
    AutoApprove {
        at: DateTime<Utc>,
    },
    Approve {
        decided_by: u64,
        at: DateTime<Utc>,
    },
    Decline {
        decided_by: u64,
        at: DateTime<Utc>,
        reason: Option<String>,
    },
    Expire {
        at: DateTime<Utc>,
    },
}

/// Re-read invitation link, reject if not is_active, insert pending request,
/// emit `request.created`, return next-step instruction.
pub async fn pre_decision_logic(
    state: &AppState,
    input: &SubmitRequestInput,
    now: DateTime<Utc>,
    request_id: Option<String>,
) -> crate::error::Result<PreDecisionOutcome> {
    let link = state
        .storage
        .get_invitation_link_by_id(input.invitation_link_id)
        .await?
        .ok_or(HandlerError::Storage(
            ghinvite_core::storage::Error::NotFound,
        ))?;

    if !link.is_active(now) {
        return Err(HandlerError::Storage(
            ghinvite_core::storage::Error::NotFound,
        ));
    }

    let request = DomainInvitationRequest {
        id: input.request_id,
        invitation_link_id: input.invitation_link_id,
        requester_id: input.requester_id,
        justification: input.justification.clone(),
        state: RequestState::Pending,
        decided_by: None,
        decided_at: None,
        decline_reason: None,
        created_at: input.created_at,
    };
    state
        .storage
        .insert_invitation_request_and_increment_uses(&request)
        .await?;

    crate::audit::emit(
        state,
        link.account_id,
        EventType::RequestCreated,
        Actor::User(input.requester_id),
        Target::request(input.request_id),
        serde_json::json!({
            "invitation_link_id": input.invitation_link_id.to_string(),
            "auto_approve": !link.approval_required,
        }),
        request_id,
    )
    .await?;

    if !link.approval_required {
        return Ok(PreDecisionOutcome::AutoApprove {
            account_id: link.account_id,
        });
    }

    let deadline = match link.expires_at {
        Some(e) => std::cmp::min(e, now + MAX_DECISION_WAIT),
        None => now + MAX_DECISION_WAIT,
    };
    Ok(PreDecisionOutcome::PendingDecision {
        account_id: link.account_id,
        decision_deadline: deadline,
    })
}

/// Apply an Approve/Decline/AutoApprove/Expire decision and emit the audit event.
/// Idempotent: a second call after the row is already terminal returns Ok.
pub async fn apply_decision_logic(
    state: &AppState,
    request_id: RequestId,
    account_id: u64,
    decision: AppliedDecision,
    request_id_for_audit: Option<String>,
) -> crate::error::Result<RequestState> {
    match decision {
        AppliedDecision::Approve { decided_by, at } => {
            approve_request_transition(
                state,
                request_id,
                account_id,
                decided_by,
                at,
                request_id_for_audit,
            )
            .await
        }
        AppliedDecision::AutoApprove { at } => {
            auto_approve_request_transition(state, request_id, account_id, at, request_id_for_audit)
                .await
        }
        AppliedDecision::Decline {
            decided_by,
            at,
            reason,
        } => {
            decline_request_transition(
                state,
                request_id,
                account_id,
                decided_by,
                at,
                reason,
                request_id_for_audit,
            )
            .await
        }
        AppliedDecision::Expire { at } => {
            expire_request_transition(state, request_id, account_id, at, request_id_for_audit).await
        }
    }
}

async fn approve_request_transition(
    state: &AppState,
    request_id: RequestId,
    account_id: u64,
    decided_by: u64,
    decided_at: DateTime<Utc>,
    request_id_for_audit: Option<String>,
) -> crate::error::Result<RequestState> {
    record_request_transition(
        state,
        ghinvite_core::storage::RequestDecision {
            request_id,
            state: RequestState::Approved,
            decided_by: Some(decided_by),
            decided_at,
            decline_reason: None,
        },
        account_id,
        EventType::RequestApproved,
        Actor::User(decided_by),
        serde_json::json!({}),
        request_id_for_audit,
    )
    .await
}

async fn auto_approve_request_transition(
    state: &AppState,
    request_id: RequestId,
    account_id: u64,
    approved_at: DateTime<Utc>,
    request_id_for_audit: Option<String>,
) -> crate::error::Result<RequestState> {
    record_request_transition(
        state,
        ghinvite_core::storage::RequestDecision {
            request_id,
            state: RequestState::Approved,
            decided_by: None,
            decided_at: approved_at,
            decline_reason: None,
        },
        account_id,
        EventType::RequestApproved,
        Actor::System,
        serde_json::json!({"reason": "auto_approve"}),
        request_id_for_audit,
    )
    .await
}

async fn decline_request_transition(
    state: &AppState,
    request_id: RequestId,
    account_id: u64,
    decided_by: u64,
    decided_at: DateTime<Utc>,
    reason: Option<String>,
    request_id_for_audit: Option<String>,
) -> crate::error::Result<RequestState> {
    let decline_reason_present = reason.is_some();
    record_request_transition(
        state,
        ghinvite_core::storage::RequestDecision {
            request_id,
            state: RequestState::Declined,
            decided_by: Some(decided_by),
            decided_at,
            decline_reason: reason,
        },
        account_id,
        EventType::RequestDeclined,
        Actor::User(decided_by),
        serde_json::json!({"decline_reason_present": decline_reason_present}),
        request_id_for_audit,
    )
    .await
}

async fn expire_request_transition(
    state: &AppState,
    request_id: RequestId,
    account_id: u64,
    expired_at: DateTime<Utc>,
    request_id_for_audit: Option<String>,
) -> crate::error::Result<RequestState> {
    record_request_transition(
        state,
        ghinvite_core::storage::RequestDecision {
            request_id,
            state: RequestState::Expired,
            decided_by: None,
            decided_at: expired_at,
            decline_reason: None,
        },
        account_id,
        EventType::RequestExpired,
        Actor::System,
        serde_json::json!({"reason": "timeout"}),
        request_id_for_audit,
    )
    .await
}

async fn record_request_transition(
    state: &AppState,
    decision: ghinvite_core::storage::RequestDecision,
    account_id: u64,
    event_type: EventType,
    actor: Actor,
    metadata: serde_json::Value,
    request_id_for_audit: Option<String>,
) -> crate::error::Result<RequestState> {
    let request_id = decision.request_id;
    let new_state = decision.state;
    let req = state
        .storage
        .get_invitation_request(request_id)
        .await?
        .ok_or(HandlerError::Storage(
            ghinvite_core::storage::Error::NotFound,
        ))?;
    if req.state.is_terminal() {
        return Ok(req.state);
    }

    match state.storage.record_request_decision(&decision).await {
        Ok(()) => (),
        Err(ghinvite_core::storage::Error::NotFound) => {
            let current = state
                .storage
                .get_invitation_request(request_id)
                .await?
                .ok_or(HandlerError::Storage(
                    ghinvite_core::storage::Error::NotFound,
                ))?;
            return Ok(current.state);
        }
        Err(e) => return Err(e.into()),
    }

    crate::audit::emit(
        state,
        account_id,
        event_type,
        actor,
        Target::request(request_id),
        metadata,
        request_id_for_audit,
    )
    .await?;

    Ok(new_state)
}

/// Pure logic: read the request's invitation_link and build CreateInvitationInput
/// per repo. Emits no audit (each `GithubInvitation::create` is responsible
/// for its own).
pub async fn build_dispatch_inputs(
    state: &AppState,
    request_id: RequestId,
    now: DateTime<Utc>,
) -> crate::error::Result<Vec<crate::github_invitation::CreateInvitationInput>> {
    let context =
        crate::invitation_context::load_invitation_request_context(state, request_id).await?;
    let invitation_request_id = context.request.id;
    let installation_id = context.link.installation_id;
    let permission = context.link.permission;
    let recipient_login = context.requester.login;

    Ok(context
        .link
        .repos
        .into_iter()
        .map(|r| crate::github_invitation::CreateInvitationInput {
            invitation_id: ghinvite_core::GithubInvitationId::new(),
            invitation_request_id,
            installation_id,
            repo_id: r.repo_id,
            repo_full_name: r.repo_full_name,
            recipient_login: recipient_login.clone(),
            permission,
            now,
        })
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_support::{dt, fixture_state, fixture_state_with_storage};
    use ghinvite_core::audit::{ActorKind, EventType, TargetKind};
    use ghinvite_core::{
        AccountType, InvitationLink, InvitationLinkId, Permission, SelectedRepos, Slug,
    };
    use rand::SeedableRng;

    async fn seed_link(
        state: &AppState,
        approval_required: bool,
        expires_at: Option<DateTime<Utc>>,
    ) -> InvitationLinkId {
        state
            .storage
            .insert_installation(&ghinvite_core::Account {
                installation_id: 1,
                account_id: 100,
                account_login: "acme".into(),
                account_type: AccountType::Organization,
                installed_at: dt("2026-05-04T12:00:00Z"),
                uninstalled_at: None,
                selected_repos: SelectedRepos::All,
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&ghinvite_core::User {
                user_id: 7,
                login: "creator".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&ghinvite_core::User {
                user_id: 8,
                login: "alice".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        let link = InvitationLink {
            id: InvitationLinkId::new(),
            slug: Slug::generate(&mut rand_chacha::ChaCha8Rng::seed_from_u64(99)),
            installation_id: 1,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at,
            max_uses: None,
            uses_count: 0,
            permission: Permission::Pull,
            approval_required,
            description: "AI coding workshop".into(),
            internal_note: None,
            revoked_at: None,
            revoked_by: None,
            repos: vec![],
        };
        state.storage.insert_invitation_link(&link).await.unwrap();
        link.id
    }

    async fn audit_events(
        storage: &ghinvite_storage_sqlx::SqlxStorage,
        account_id: u64,
    ) -> Vec<ghinvite_core::audit::AuditEvent> {
        storage.debug_list_audit(account_id).await.unwrap()
    }

    #[tokio::test]
    async fn pre_decision_auto_approve_when_link_doesnt_require() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, false, None).await;
        let req_id = RequestId::new();

        let outcome = pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();
        assert!(matches!(outcome, PreDecisionOutcome::AutoApprove { .. }));

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(req.state, RequestState::Pending); // pre-decision only inserts pending
    }

    #[tokio::test]
    async fn pre_decision_pending_with_deadline_capped_at_7d() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, None).await;

        let outcome = pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: RequestId::new(),
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        match outcome {
            PreDecisionOutcome::PendingDecision {
                decision_deadline, ..
            } => {
                assert_eq!(
                    decision_deadline,
                    dt("2026-05-04T12:30:00Z") + Duration::days(7)
                );
            }
            other => panic!("expected PendingDecision, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn pre_decision_pending_uses_link_expires_when_sooner() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, Some(dt("2026-05-06T12:00:00Z"))).await;

        let outcome = pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: RequestId::new(),
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        match outcome {
            PreDecisionOutcome::PendingDecision {
                decision_deadline, ..
            } => {
                assert_eq!(decision_deadline, dt("2026-05-06T12:00:00Z"));
            }
            other => panic!("expected PendingDecision, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn pre_decision_inactive_link_is_terminal() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, false, Some(dt("2026-05-03T00:00:00Z"))).await;

        let err = pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: RequestId::new(),
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap_err();
        assert!(err.is_terminal());
    }

    #[tokio::test]
    async fn apply_decision_approve_records_and_audits() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, None).await;
        let req_id = RequestId::new();
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        let final_state = apply_decision_logic(
            &state,
            req_id,
            100,
            AppliedDecision::Approve {
                decided_by: 7,
                at: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();
        assert_eq!(final_state, RequestState::Approved);

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(req.state, RequestState::Approved);
        assert_eq!(req.decided_by, Some(7));
    }

    #[tokio::test]
    async fn approve_transition_owns_state_and_audit() {
        let (state, storage) = fixture_state_with_storage().await;
        let link_id = seed_link(&state, true, None).await;
        let req_id = RequestId::new();
        let decided_at = dt("2026-05-04T13:00:00Z");
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        let final_state = approve_request_transition(
            &state,
            req_id,
            100,
            7,
            decided_at,
            Some("req-approve".into()),
        )
        .await
        .unwrap();
        assert_eq!(final_state, RequestState::Approved);

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(req.state, RequestState::Approved);
        assert_eq!(req.decided_by, Some(7));
        assert_eq!(req.decided_at, Some(decided_at));
        assert_eq!(req.decline_reason, None);

        let audits = audit_events(&storage, 100).await;
        let event = audits
            .iter()
            .find(|event| event.event_type == EventType::RequestApproved)
            .expect("approval should emit audit event");
        assert_eq!(event.actor_kind, ActorKind::User);
        assert_eq!(event.actor_id, Some(7));
        assert_eq!(event.target_kind, TargetKind::InvitationRequest);
        assert_eq!(event.target_id, req_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-approve"));
        assert_eq!(event.metadata, serde_json::json!({}));
    }

    #[tokio::test]
    async fn apply_decision_decline_with_reason() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, None).await;
        let req_id = RequestId::new();
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        let final_state = apply_decision_logic(
            &state,
            req_id,
            100,
            AppliedDecision::Decline {
                decided_by: 7,
                at: dt("2026-05-04T13:00:00Z"),
                reason: Some("not familiar with this user".into()),
            },
            None,
        )
        .await
        .unwrap();
        assert_eq!(final_state, RequestState::Declined);

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(
            req.decline_reason.as_deref(),
            Some("not familiar with this user")
        );
    }

    #[tokio::test]
    async fn decline_transition_owns_state_and_audit() {
        let (state, storage) = fixture_state_with_storage().await;
        let link_id = seed_link(&state, true, None).await;
        let req_id = RequestId::new();
        let decided_at = dt("2026-05-04T13:00:00Z");
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        let final_state = decline_request_transition(
            &state,
            req_id,
            100,
            7,
            decided_at,
            Some("not familiar with this user".into()),
            Some("req-decline".into()),
        )
        .await
        .unwrap();
        assert_eq!(final_state, RequestState::Declined);

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(req.state, RequestState::Declined);
        assert_eq!(req.decided_by, Some(7));
        assert_eq!(req.decided_at, Some(decided_at));
        assert_eq!(
            req.decline_reason.as_deref(),
            Some("not familiar with this user")
        );

        let audits = audit_events(&storage, 100).await;
        let event = audits
            .iter()
            .find(|event| event.event_type == EventType::RequestDeclined)
            .expect("decline should emit audit event");
        assert_eq!(event.actor_kind, ActorKind::User);
        assert_eq!(event.actor_id, Some(7));
        assert_eq!(event.target_kind, TargetKind::InvitationRequest);
        assert_eq!(event.target_id, req_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-decline"));
        assert_eq!(
            event.metadata.get("decline_reason_present"),
            Some(&serde_json::json!(true))
        );
    }

    #[tokio::test]
    async fn build_dispatch_inputs_emits_one_per_repo() {
        let state = fixture_state().await;
        // Seed installation + users (same fixture chain as `seed_link`).
        state
            .storage
            .insert_installation(&ghinvite_core::Account {
                installation_id: 1,
                account_id: 100,
                account_login: "acme".into(),
                account_type: AccountType::Organization,
                installed_at: dt("2026-05-04T12:00:00Z"),
                uninstalled_at: None,
                selected_repos: SelectedRepos::All,
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&ghinvite_core::User {
                user_id: 7,
                login: "creator".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();
        state
            .storage
            .upsert_user(&ghinvite_core::User {
                user_id: 8,
                login: "alice".into(),
                avatar_url: None,
                last_seen_at: dt("2026-05-04T12:00:00Z"),
            })
            .await
            .unwrap();

        // Link with two repos so we can assert the fan-out shape.
        let link = InvitationLink {
            id: InvitationLinkId::new(),
            slug: Slug::generate(&mut rand_chacha::ChaCha8Rng::seed_from_u64(101)),
            installation_id: 1,
            account_id: 100,
            created_by: 7,
            created_at: dt("2026-05-04T12:00:00Z"),
            expires_at: None,
            max_uses: None,
            uses_count: 0,
            permission: Permission::Push,
            approval_required: false, // auto-approve so the workflow path is exercised
            description: "AI coding workshop".into(),
            internal_note: None,
            revoked_at: None,
            revoked_by: None,
            repos: vec![
                ghinvite_core::InvitationLinkRepo {
                    repo_id: 10,
                    repo_full_name: "acme/api".into(),
                },
                ghinvite_core::InvitationLinkRepo {
                    repo_id: 11,
                    repo_full_name: "acme/web".into(),
                },
            ],
        };
        state.storage.insert_invitation_link(&link).await.unwrap();

        let req_id = RequestId::new();
        let now = dt("2026-05-04T12:30:00Z");
        let outcome = pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link.id,
                requester_id: 8,
                justification: None,
                created_at: now,
            },
            now,
            None,
        )
        .await
        .unwrap();
        assert!(matches!(outcome, PreDecisionOutcome::AutoApprove { .. }));

        apply_decision_logic(
            &state,
            req_id,
            100,
            AppliedDecision::AutoApprove { at: now },
            None,
        )
        .await
        .unwrap();

        let inputs = build_dispatch_inputs(&state, req_id, now).await.unwrap();
        assert_eq!(inputs.len(), 2);
        // Both inputs should reference the same request, recipient, and
        // installation; the per-repo fields differ.
        for inp in &inputs {
            assert_eq!(inp.invitation_request_id, req_id);
            assert_eq!(inp.installation_id, 1);
            assert_eq!(inp.recipient_login, "alice");
            assert_eq!(inp.permission, Permission::Push);
            assert_eq!(inp.now, now);
        }
        let mut full_names: Vec<&str> = inputs.iter().map(|i| i.repo_full_name.as_str()).collect();
        full_names.sort();
        assert_eq!(full_names, vec!["acme/api", "acme/web"]);
        let mut repo_ids: Vec<u64> = inputs.iter().map(|i| i.repo_id).collect();
        repo_ids.sort();
        assert_eq!(repo_ids, vec![10, 11]);
    }

    #[tokio::test]
    async fn apply_decision_auto_approve_records_no_decider() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, false, None).await;
        let req_id = RequestId::new();
        let now = dt("2026-05-04T12:30:00Z");
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: now,
            },
            now,
            None,
        )
        .await
        .unwrap();

        let final_state = apply_decision_logic(
            &state,
            req_id,
            100,
            AppliedDecision::AutoApprove { at: now },
            None,
        )
        .await
        .unwrap();
        assert_eq!(final_state, RequestState::Approved);

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert!(
            req.decided_by.is_none(),
            "auto-approved request should have no human decider"
        );
    }

    #[tokio::test]
    async fn auto_approve_transition_owns_state_and_audit() {
        let (state, storage) = fixture_state_with_storage().await;
        let link_id = seed_link(&state, false, None).await;
        let req_id = RequestId::new();
        let now = dt("2026-05-04T12:30:00Z");
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: now,
            },
            now,
            None,
        )
        .await
        .unwrap();

        let final_state = auto_approve_request_transition(
            &state,
            req_id,
            100,
            now,
            Some("req-auto-approve".into()),
        )
        .await
        .unwrap();
        assert_eq!(final_state, RequestState::Approved);

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(req.state, RequestState::Approved);
        assert_eq!(req.decided_by, None);
        assert_eq!(req.decided_at, Some(now));
        assert_eq!(req.decline_reason, None);

        let audits = audit_events(&storage, 100).await;
        let event = audits
            .iter()
            .find(|event| event.event_type == EventType::RequestApproved)
            .expect("auto approval should emit audit event");
        assert_eq!(event.actor_kind, ActorKind::System);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::InvitationRequest);
        assert_eq!(event.target_id, req_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-auto-approve"));
        assert_eq!(
            event.metadata.get("reason"),
            Some(&serde_json::json!("auto_approve"))
        );
    }

    #[tokio::test]
    async fn expire_transition_owns_state_and_audit() {
        let (state, storage) = fixture_state_with_storage().await;
        let link_id = seed_link(&state, true, None).await;
        let req_id = RequestId::new();
        let expired_at = dt("2026-05-11T12:30:00Z");
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        let final_state =
            expire_request_transition(&state, req_id, 100, expired_at, Some("req-expire".into()))
                .await
                .unwrap();
        assert_eq!(final_state, RequestState::Expired);

        let req = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(req.state, RequestState::Expired);
        assert_eq!(req.decided_by, None);
        assert_eq!(req.decided_at, Some(expired_at));
        assert_eq!(req.decline_reason, None);

        let audits = audit_events(&storage, 100).await;
        let event = audits
            .iter()
            .find(|event| event.event_type == EventType::RequestExpired)
            .expect("expiration should emit audit event");
        assert_eq!(event.actor_kind, ActorKind::System);
        assert_eq!(event.actor_id, None);
        assert_eq!(event.target_kind, TargetKind::InvitationRequest);
        assert_eq!(event.target_id, req_id.to_string());
        assert_eq!(event.request_id.as_deref(), Some("req-expire"));
        assert_eq!(
            event.metadata.get("reason"),
            Some(&serde_json::json!("timeout"))
        );
    }

    #[tokio::test]
    async fn apply_decision_idempotent_after_first_decision() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, None).await;
        let req_id = RequestId::new();
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        apply_decision_logic(
            &state,
            req_id,
            100,
            AppliedDecision::Approve {
                decided_by: 7,
                at: dt("2026-05-04T13:00:00Z"),
            },
            None,
        )
        .await
        .unwrap();

        // Second decision call returns the existing state, no re-audit.
        let result = apply_decision_logic(
            &state,
            req_id,
            100,
            AppliedDecision::Decline {
                decided_by: 7,
                at: dt("2026-05-04T14:00:00Z"),
                reason: Some("changed mind".into()),
            },
            None,
        )
        .await
        .unwrap();
        assert_eq!(result, RequestState::Approved, "first decision wins");
    }

    #[tokio::test]
    async fn racing_transitions_return_the_winning_terminal_state() {
        let state = fixture_state().await;
        let link_id = seed_link(&state, true, None).await;
        let req_id = RequestId::new();
        pre_decision_logic(
            &state,
            &SubmitRequestInput {
                request_id: req_id,
                invitation_link_id: link_id,
                requester_id: 8,
                justification: None,
                created_at: dt("2026-05-04T12:30:00Z"),
            },
            dt("2026-05-04T12:30:00Z"),
            None,
        )
        .await
        .unwrap();

        let start = std::sync::Arc::new(tokio::sync::Barrier::new(32));
        let mut handles = Vec::new();
        for index in 0..32 {
            let state = state.clone();
            let start = start.clone();
            handles.push(tokio::spawn(async move {
                start.wait().await;
                if index % 2 == 0 {
                    approve_request_transition(
                        &state,
                        req_id,
                        100,
                        7,
                        dt("2026-05-04T13:00:00Z"),
                        None,
                    )
                    .await
                } else {
                    decline_request_transition(
                        &state,
                        req_id,
                        100,
                        7,
                        dt("2026-05-04T13:00:00Z"),
                        Some("raced".into()),
                        None,
                    )
                    .await
                }
            }));
        }

        let mut returned_states = Vec::new();
        for handle in handles {
            returned_states.push(handle.await.unwrap().unwrap());
        }

        let stored_state = state
            .storage
            .get_invitation_request(req_id)
            .await
            .unwrap()
            .unwrap()
            .state;
        assert!(stored_state.is_terminal());
        assert!(
            returned_states.iter().all(|state| *state == stored_state),
            "all racing callers should observe {stored_state:?}, got {returned_states:?}"
        );
    }
}
